import{_ as e,d as t,f as n,i as r,l as i,r as a,t as o,u as s}from"./src-GO5ZQO2t.js";var c=t(),l=e(n(),1),u=i();function d(e){let t={a:`a`,code:`code`,h2:`h2`,h3:`h3`,img:`img`,li:`li`,p:`p`,strong:`strong`,ul:`ul`,...e.components};return(0,u.jsxs)(u.Fragment,{children:[(0,u.jsxs)(t.p,{children:[`Today, we are releasing the latest version of our flagship model: `,(0,u.jsx)(t.strong,{children:`GLM-4.6`}),`. Compared with GLM-4.5, this generation brings several key improvements:`]}),`
`,(0,u.jsxs)(t.ul,{children:[`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`Longer context window:`}),` The context window has been expanded from 128K to 200K tokens, enabling the model to handle more complex agentic tasks.`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`Superior coding performance:`}),` The model achieves higher scores on code benchmarks and demonstrates better real-world performance in applications such as Claude Code、Cline、Roo Code and Kilo Code, including improvements in generating visually polished front-end pages.`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`Advanced reasoning:`}),` GLM-4.6 shows a clear improvement in reasoning performance and supports tool use during inference, leading to stronger overall capability.`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`More capable agents:`}),` GLM-4.6 exhibits stronger performance in tool using and search-based agents, and integrates more effectively within agent frameworks.`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`Refined writing:`}),` Better aligns with human preferences in style and readability, and performs more naturally in role-playing scenarios.`]}),`
`]}),`
`,(0,u.jsxs)(t.p,{children:[`We evaluated GLM-4.6 across eight public benchmarks covering agents, reasoning, and coding. Results show clear gains over GLM-4.5, with GLM-4.6 also holding competitive advantages over leading domestic and international models such as `,(0,u.jsx)(t.strong,{children:`DeepSeek-V3.2-Exp`}),` and `,(0,u.jsx)(t.strong,{children:`Claude Sonnet 4`}),`, but still lags behind Claude Sonnet 4.5 in coding ability.`]}),`
`,(0,u.jsx)(t.p,{children:(0,u.jsx)(t.img,{src:`https://z-cdn.chatglm.cn/z-blog/glm-4-6/coding_benchmark.png`,alt:``})}),`
`,(0,u.jsxs)(t.p,{children:[`Real-world experience matters more than leaderboards. We extended `,(0,u.jsx)(t.strong,{children:`CC-Bench`}),` from GLM-4.5 with more challenging tasks, where human evaluators worked with models inside isolated Docker containers and completed multi-turn real-world tasks across front-end development, tool building, data analysis, testing, and algorithm. `,(0,u.jsx)(t.strong,{children:`GLM-4.6`}),` improves over GLM-4.5 and reaches `,(0,u.jsx)(t.strong,{children:`near parity with Claude Sonnet 4 (48.6% win rate)`}),`, while clearly outperforming other open-source baselines. From a `,(0,u.jsx)(t.strong,{children:`token-efficiency`}),` perspective, GLM-4.6 finishes tasks with about 15% fewer tokens than GLM-4.5, showing improvements in both capability and efficiency. All evaluation details and trajectory data have been made publicly available for further community research: `,(0,u.jsx)(t.a,{href:`https://huggingface.co/datasets/zai-org/CC-Bench-trajectories`,children:`https://huggingface.co/datasets/zai-org/CC-Bench-trajectories`})]}),`
`,(0,u.jsx)(t.p,{children:(0,u.jsx)(t.img,{src:`https://z-cdn.chatglm.cn/z-blog/glm-4-6/perf.png`,alt:``})}),`
`,(0,u.jsx)(t.h2,{children:`Getting started with GLM-4.6`}),`
`,(0,u.jsx)(t.h3,{children:`Call GLM-4.6 API on Z.ai API platform`}),`
`,(0,u.jsxs)(t.p,{children:[`The Z.ai API platform offers both GLM-4.6 models. For comprehensive API documentation and integration guidelines, please refer to `,(0,u.jsx)(t.a,{href:`https://docs.z.ai/guides/llm/glm-4.6`,children:`https://docs.z.ai/guides/llm/glm-4.6`}),`. Alternatively, developers are welcome to access both models through OpenRouter.`]}),`
`,(0,u.jsx)(t.h3,{children:`Use GLM-4.6 with Coding Agents`}),`
`,(0,u.jsx)(t.p,{children:`GLM-4.6 is now available to use within coding agents (Claude Code, Kilo Code, Roo Code, Cline and more).`}),`
`,(0,u.jsxs)(t.p,{children:[`For `,(0,u.jsx)(t.strong,{children:`GLM Coding Plan subscribers`}),`: You'll be automatically upgraded to GLM-4.6. If you've previously customized the app configs (like `,(0,u.jsx)(t.code,{children:`~/.claude/settings.json`}),` in Claude Code), simply update the model name to `,(0,u.jsx)(t.code,{children:`"glm-4.6"`}),` to complete the upgrade.`]}),`
`,(0,u.jsxs)(t.p,{children:[`For `,(0,u.jsx)(t.strong,{children:`New users`}),`: The GLM Coding Plan offers Claude-level performance at a fraction of the cost — just 1/7th the price with 3x the usage quota. Start building today: `,(0,u.jsx)(t.a,{href:`https://z.ai/subscribe`,children:`https://z.ai/subscribe`}),`.`]}),`
`,(0,u.jsx)(t.h3,{children:`Chat with GLM-4.6 on Z.ai`}),`
`,(0,u.jsxs)(t.p,{children:[`GLM-4.6 is accessible through `,(0,u.jsx)(t.a,{href:`https://chat.z.ai`,children:`Z.ai`}),` by selecting the GLM-4.6 model option.`]}),`
`,(0,u.jsx)(t.h3,{children:`Serve GLM-4.6 Locally`}),`
`,(0,u.jsxs)(t.p,{children:[`Model weights of GLM-4.6 is publicly available at `,(0,u.jsx)(t.a,{href:`https://huggingface.co/zai-org/GLM-4.6`,children:`HuggingFace`}),` and `,(0,u.jsx)(t.a,{href:`https://modelscope.cn/models/ZhipuAI/GLM-4.6`,children:`ModelScope`}),`. For local deployment, GLM-4.6 supports inference frameworks including vLLM and SGLang. Comprehensive deployment instructions are available in the official GitHub repository.`]})]})}function f(e={}){let{wrapper:t}=e.components||{};return t?(0,u.jsx)(t,{...e,children:(0,u.jsx)(d,{...e})}):d(e)}function p(e){let t={a:`a`,code:`code`,h2:`h2`,h3:`h3`,img:`img`,li:`li`,p:`p`,strong:`strong`,ul:`ul`,...e.components};return(0,u.jsxs)(u.Fragment,{children:[(0,u.jsx)(t.p,{children:`今天，我们发布旗舰模型的最新版本 GLM-4.6。相比 GLM-4.5，本代模型的提升如下:`}),`
`,(0,u.jsxs)(t.ul,{children:[`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`更长的上下文窗口`}),`： 上下文窗口从 128K 提升至 200K，适应更长的代码和智能体任务。`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`综合代码能力提升`}),`： 在代码公开基准评估的得分与 Claude Code、Cline、Roo Code 和 Kilo Code 等智能体应用上的实际效果提升，编写前端页面时的美观度进一步改善。`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`更先进的推理能力`}),`： 模型的推理能力取得了提升，并支持在推理过程中调用工具，综合性能更强。`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`更强的智能体能力`}),`： 增强了模型在工具调用和搜索智能体上的表现，在智能体框架中的表现更好。`]}),`
`,(0,u.jsxs)(t.li,{children:[(0,u.jsx)(t.strong,{children:`写作能力提升`}),`： 在风格和可读性上更贴合人类偏好，并在角色扮演场景中表现更自然。`]}),`
`]}),`
`,(0,u.jsx)(t.p,{children:`我们在涵盖智能体、推理、代码的 8 项公开基准评估上对 GLM-4.6 的表现进行了评估，结果显示 GLM-4.5 相比上一代模型有较为明显的提升，对比国内外主流模型（DeepSeek-V3.2-Exp、Claude Sonnet 4）具有一定的性能优势，但和 Claude Sonnet 4.5 在代码能力上还有一定的差距。`}),`
`,(0,u.jsx)(t.p,{children:(0,u.jsx)(t.img,{src:`https://z-cdn.chatglm.cn/z-blog/glm-4-6/coding_benchmark.png`,alt:``})}),`
`,(0,u.jsxs)(t.p,{children:[`真实场景体验比榜单更重要，我们延续了 GLM-4.5 的 CC-Bench 评测基准，评估人员在独立的 Docker 容器环境中，以多轮人机协作方式，全面评估模型在前端开发、工具开发、数据分析、测试和算法实现等多个开发实战领域的表现。本次题目难度进一步提升，从效果角度来看，GLM-4.6 相较 GLM-4.5 有实质提升，性能比肩 Claude Sonnet 4（48.6% 胜率），明显优于其他开源模型；从效率角度来看，GLM-4.6 相比 GLM-4.5 需要的 token 数减少约 15%，做到更强且更省——智能水平与使用效率双提升。评测方法与 Agent 轨迹开源，便于社区复现与研究：`,(0,u.jsx)(t.a,{href:`https://huggingface.co/datasets/zai-org/CC-Bench-trajectories`,children:`https://huggingface.co/datasets/zai-org/CC-Bench-trajectories`})]}),`
`,(0,u.jsx)(t.p,{children:(0,u.jsx)(t.img,{src:`https://z-cdn.chatglm.cn/z-blog/glm-4-6/perf.png`,alt:``})}),`
`,(0,u.jsx)(t.h2,{children:`开始使用 GLM-4.6`}),`
`,(0,u.jsx)(t.h3,{children:`在 Z.ai 上与 GLM-4.6 聊天`}),`
`,(0,u.jsxs)(t.p,{children:[`GLM-4.6 可通过 `,(0,u.jsx)(t.a,{href:`https://chat.z.ai`,children:`Z.ai`}),` 平台访问，该平台支持前端页面生成、PPT 生成和全栈开发能力。`]}),`
`,(0,u.jsx)(t.h3,{children:`在 BigModel.cn 上调用 GLM-4.6 API`}),`
`,(0,u.jsxs)(t.p,{children:[`BigModel API 平台 为 GLM-4.6 模型提供 OpenAI 兼容的接口。有关全面的 API 文档和集成指南，请参考`,(0,u.jsx)(t.a,{href:`https://docs.bigmodel.cn/cn/guide/models/text/glm-4.5`,children:`此文档`}),`。`]}),`
`,(0,u.jsx)(t.h3,{children:`将 GLM-4.6 与编码智能体一起使用`}),`
`,(0,u.jsx)(t.p,{children:`GLM-4.6现已可在各种编码智能体应用中使用（Claude Code, Kilo Code, Roo Code, Cline等）。`}),`
`,(0,u.jsxs)(t.p,{children:[`对于 `,(0,u.jsx)(t.strong,{children:`GLM Coding Plan`}),` 订阅用户：您将自动升级至 GLM-4.6。如果您之前自定义过应用配置（如 Claude Code 中的 `,(0,u.jsx)(t.code,{children:`~/.claude/settings.json`}),`），只需将模型名称更新为 `,(0,u.jsx)(t.code,{children:`"glm-4.6"`}),` 即可完成升级。`]}),`
`,(0,u.jsxs)(t.p,{children:[`对于`,(0,u.jsx)(t.strong,{children:`新用户`}),`：订阅 GLM Coding Plan 意味着以极低的成本获得媲美 Claude 的性能——仅需 1/7 的价格，即可获得 3 倍的使用额度。订阅地址：`,(0,u.jsx)(t.a,{href:`https://z.ai/subscribe`,children:`https://z.ai/subscribe`}),`。`]}),`
`,(0,u.jsx)(t.h3,{children:`本地部署 GLM-4.6`}),`
`,(0,u.jsxs)(t.p,{children:[`GLM-4.6 权重在 `,(0,u.jsx)(t.a,{href:`https://huggingface.co/zai-org/GLM-4.6`,children:`HuggingFace`}),` 和 `,(0,u.jsx)(t.a,{href:`https://modelscope.cn/models/ZhipuAI/GLM-4.6`,children:`ModelScope`}),` 上公开可用。对于本地部署，GLM-4.6 支持包括 vLLM 和 SGLang 在内的推理框架。全面的部署说明，详见官方 GitHub 仓库。`]})]})}function m(e={}){let{wrapper:t}=e.components||{};return t?(0,u.jsx)(t,{...e,children:(0,u.jsx)(p,{...e})}):p(e)}(0,c.createRoot)(document.getElementById(`root`)).render((0,u.jsx)(l.StrictMode,{children:(0,u.jsx)(a,{date:`2025-09-30`,title:{en:`GLM-4.6: Advanced Agentic, Reasoning and Coding Capabilities`,zh:`GLM-4.6：更强大的智能体、推理和代码能力`},document:{en:`https://docs.z.ai/guides/llm/glm-4.6`,zh:`https://docs.bigmodel.cn/cn/guide/models/text/glm-4.6`},huggingface:`https://huggingface.co/zai-org/GLM-4.6`,report:`https://arxiv.org/abs/2508.06471`,children:(0,u.jsx)(s,{children:(0,u.jsx)(r,{en:f,zh:m,components:o})})})}));