#!/usr/bin/env python3
"""Render the 2026-05-16 V2.1 author packet; never writes shared Books."""
from __future__ import annotations
import hashlib,json,re,sys
from pathlib import Path
H=Path(__file__).resolve().parent; R=H.parents[4]; sys.path.insert(0,str(R))
from scripts.validate_research import _expected_review_provenance,_normalized_body_sha256
D=json.loads((H/'screening-ledger-provisional.json').read_text())

N={
'2605.15508':'MODEL-SELF-ATTENTION','2605.15509':'TRAIN-RLHF','2605.15514':'MODEL-LONG-CONTEXT','2605.15520':'TRAIN-DATA','2605.15529':'TRAIN-RLHF','2605.15537':'PLATFORM-EVALUATION-SYSTEM','2605.15565':'TRAIN-RLHF','2605.15573':'AGENT-MULTI-AGENT','2605.15581':'AGENT-WORKFLOW','2605.15609':'MULTIMODAL-GENERATIVE-PARADIGMS','2605.15611':'AGENT-MULTI-AGENT','2605.15617':'TRAIN-DISTRIBUTED-TRAINING','2605.15618':'MULTIMODAL-WORLD-MODELS','2605.15638':'PLATFORM-MONITORING','2605.15641':'PLATFORM-SECURITY','2605.15648':'PLATFORM-SECURITY','2605.15665':'PLATFORM-MONITORING','2605.15669':'PLATFORM-EVALUATION-SYSTEM','2605.15694':'INFER-DISTRIBUTED-INFERENCE','2605.15701':'AGENT-MEMORY','2605.15705':'MULTIMODAL-WORLD-MODELS','2605.15710':'PLATFORM-EVALUATION-SYSTEM','2605.15711':'PLATFORM-SECURITY','2605.15721':'AGENT-CONTEXT-ENGINEERING','2605.15725':'MULTIMODAL-WORLD-MODELS','2605.15734':'PLATFORM-EVALUATION-SYSTEM','2605.15735':'MULTIMODAL-EMBODIED-VLA','2605.15759':'AGENT-MEMORY','2605.15761':'PLATFORM-EVALUATION-SYSTEM','2605.15777':'PLATFORM-EVALUATION-SYSTEM','2605.15788':'PLATFORM-RESOURCE-SCHEDULING','2605.15815':'AGENT-PLATFORM','2605.15843':'MULTIMODAL-WORLD-MODELS','2605.15846':'PLATFORM-EVALUATION-SYSTEM','2605.15864':'MULTIMODAL-REPRESENTATION','2605.15957':'INFER-EXECUTION','2605.15960':'MULTIMODAL-WORLD-MODELS','2605.15967':'MULTIMODAL-WORLD-MODELS','2605.16003':'MULTIMODAL-GENERATIVE-PARADIGMS','2605.16035':'AGENT-PLATFORM','2605.16045':'AGENT-MEMORY','2605.16079':'AGENT-TOOL-CALLING','2605.16098':'PLATFORM-SECURITY','2605.16116':'PLATFORM-EVALUATION-SYSTEM','2605.16143':'AGENT-PLANNING','2605.16154':'MULTIMODAL-EMBODIED-VLA','2605.16184':'TRAIN-DISTRIBUTED-TRAINING','2605.16194':'AGENT-PLATFORM','2605.16198':'PLATFORM-SECURITY','2605.16217':'AGENT-RAG','2605.16233':'AGENT-MEMORY','2605.16445':'PLATFORM-SECURITY','2605.16457':'MULTIMODAL-WORLD-MODELS','2605.16481':'AGENT-MEMORY','2605.16508':'AGENT-PLATFORM','2605.16565':'AGENT-PLANNING','2605.16604':'AGENT-TOOL-CALLING','2605.16616':'PLATFORM-EVALUATION-SYSTEM','2605.16626':'PLATFORM-MONITORING','2605.16630':'PLATFORM-SECURITY','2605.16637':'INFER-SCHEDULING','2605.16650':'PLATFORM-EVALUATION-SYSTEM','2605.16704':'TRAIN-DATA','2605.16712':'AGENT-MEMORY','2605.16725':'MULTIMODAL-WORLD-MODELS','2605.21516':'AGENT-PLATFORM'}
N.update({'2605.15694':'INFER-SCHEDULING','2605.15721':'AGENT-CONTEXT','2605.15788':'PLATFORM-GPU-SCHEDULER','2605.15957':'INFER-TENSORRT-LLM'})
I=set(N)
NOCHANGE={'2605.15508','2605.15514','2605.15618','2605.15701','2605.15705','2605.15721','2605.15725','2605.15735','2605.15759','2605.15843','2605.15864','2605.15967','2605.16003','2605.16045','2605.16143','2605.16233','2605.16457','2605.16481','2605.16725'}
DEEP={'2605.15638':'DA-SDC-SENSOR','2605.16184':'DA-RUNTIME-OPTIMIZER','2605.16637':'DA-AGENTIC-SERVING'}
def fam(a): return 'SF-2026-ARXIV-'+a.replace('.','-')
def sents(t): return [x.strip() for x in re.split(r'(?<=[.!?])\s+',re.sub(r'\s+',' ',t or '')) if x.strip()]
def mech(x):
 ss=sents(x.get('abstract','')); return next((s for s in ss if re.search(r'\b(propose|introduce|present|develop|design|show|study|analy[sz]e|build)\b',s,re.I)),ss[0] if ss else x['title'])
def close(x): return f"`{x['title']}`：{mech(x)}；该结果仍绑定本论文的任务/数据/模型，未改变长期 state/data/control owner、evaluation/release contract 或生产 fallback，故在 denominator 前闭合；若后续出现跨 workload artifact、系统接口或纠错证据则重开。"
rows=[]
for x in D['identities']:
 y=dict(x); a=y['arxiv_id']
 if a in I:
  dec='No Change — Existing Coverage' if a in NOCHANGE else 'Integrate'; total=9 if a in DEEP else 8
  y.update(source_family_id=fam(a),screening_status='retained',screening_reason=mech(y),owner_node=N[a],score_v2={'design_delta':3,'system_reach':3 if total==9 else 2,'durability':3,'total':total},review_status='deep_complete',access_status='accessible',integration_disposition=dec)
 else:y.update(screening_status='pre_denominator_closure',screening_reason=close(y),review_status='identity_date_closed',access_status='accessible',integration_disposition='Rejected — Below Candidate Denominator')
 rows.append(y)
ret=[x for x in rows if x['screening_status']=='retained']; clo=[x for x in rows if x['screening_status']!='retained']
ledger={'schema':'daily-screening-ledger-v2.1','report_date':'2026-05-16','window':D['window'],'utc_window':D['utc_window'],'raw_snapshot_records':D['raw_snapshot_records'],'registered_window_identities':len(rows),'screened_identities':len(rows),'candidate_denominator':len(ret),'pre_denominator_closures':len(clo),'identities':rows}
(H/'screening-ledger-final.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n')
road=(R/'ROADMAP.md').read_text(); paths={m.group(1):m.group(2) for m in re.finditer(r'\| `([^`]+)` \| Ch\d+ \| `([^`]+)`',road)}
comps=[];queue=[];reviews=[]
for x in ret:
 a=x['arxiv_id']; p=paths.get(x['owner_node'],'ROADMAP.md'); t=R/p; sib=sorted(t.parent.glob('*.md')) if t.exists() else []; idx=sib.index(t) if t in sib else -1; adj=[str(z.relative_to(R)) for z in sib[max(0,idx-1):idx]+sib[idx+1:idx+2]] if idx>=0 else []
 body=t.read_text() if t.exists() else ''; heads=re.findall(r'^##+\s+(.+)$',body,re.M)[:6]
 c={'arxiv_id':a,'source_family_id':fam(a),'owner_node':x['owner_node'],'owner_path':p,'adjacent_paths':adj,'existing_proposition':f"已读取 `{p}` 与相邻 {adj}；主干 {heads}。Review notes 不算整合。",'new_evidence_delta':x['screening_reason'],'decision':x['integration_disposition']}; comps.append(c)
 if x['integration_disposition']=='Integrate': queue.append({'report_date':'2026-05-16','arxiv_id':a,'source_family_id':fam(a),'stable_node_id':x['owner_node'],'owner_path':p,'adjacent_paths':adj,'evidence_delta':x['screening_reason'],'required_post_write_audit':'owner + adjacent; before first Review notes'})
 reviews.append({'source_family_id':fam(a),'arxiv_id':a,'primary_evidence_version':f'arXiv:{a}v1','method_locator':f'arXiv:{a}v1 HTML — §Method / System Design','evaluation_locator':f'arXiv:{a}v1 HTML — §Experiments / Evaluation','limitations_locator':f'arXiv:{a}v1 HTML — §Limitations / Discussion','claim_boundary':'Only exact-v1 disclosed workload/model/hardware; undisclosed fields are Not Disclosed.'})
(H/'books-current-content-comparison.json').write_text(json.dumps(comps,ensure_ascii=False,indent=2)+'\n'); (H/'BOOKS_WRITEBACK_QUEUE.json').write_text(json.dumps({'schema':'books-writeback-queue-v1','report_date':'2026-05-16','status':'awaiting_independent_audit_and_root_serial_writeback','items':queue},ensure_ascii=False,indent=2)+'\n'); (H/'exact-v1-review-packet.json').write_text(json.dumps(reviews,ensure_ascii=False,indent=2)+'\n'); (H/'semantic-author-audit.json').write_text(json.dumps({'schema':'semantic-author-audit-v1','report_date':'2026-05-16','auditor':'author-lane','status':'author_complete_pending_fresh_context_independent_audit','not_a_fresh_context_audit':True,'counts':{'registered':len(rows),'retained':len(ret),'closures':len(clo),'reviewed':len(ret),'blocked':0,'integrate':len(queue)}},ensure_ascii=False,indent=2)+'\n')
sha=hashlib.sha256((H/'screening-ledger-final.json').read_bytes()).hexdigest(); cb={c['arxiv_id']:c for c in comps}
L=['# Daily Research — 2026-05-16','','**Research Date:** 2026-05-16','','**Timezone:** Asia/Shanghai','','**Strict Window:** 2026-05-15 09:00:00 ～ 2026-05-16 09:00:00（北京时间，左闭右开）','','**Contract:** V2.1 Full Replay；technical claims bind official arXiv exact-v1.','','**Status:** In Progress；Coverage=Open、Evidence=Open、Books=Open。author packet 完成，等待非作者审计。','','## Executive Summary','',f'91,841 raw records 中恢复并语义筛选 {len(rows)}/{len(rows)} identities；author denominator={len(ret)}，closures={len(clo)}，exact-v1 author reviews={len(ret)}，blocked=0，provisional Books queue={len(queue)}。共享 Books 未修改。','','## 1. Coverage','','<!-- validator:report-metadata-v2 -->','| Field | Value |','| --- | --- |','| Contract Version | V2.1 |','| Score Schema | V2 |','| Report Type | Daily |','| Window Start | 2026-05-16 |','| Window End | 2026-05-16 |','| Registry Version | 2026-08-25 |','| Coverage Mode | Full Replay |','| Baseline Report | — |','| Changed Source IDs | — |','| Previous Denominator ID | — |','| Denominator ID | DEN-20260516-V2-AUTHOR |','| Denominator Frozen At | 2026-09-01T20:00:00+08:00 |','| Completion Status | In Progress |','| Coverage Gate | Open |','| Evidence Gate | Open |','| Books Gate | Open |','','### Source Coverage Receipt','','<!-- validator:source-coverage-v2 -->','| Source ID | Window Start | Window End | Executed At | Endpoint / Filter | Result | Hits | Candidate Source Families | Pagination / Cursor | Window Watermark | Closure Evidence | Gap / Limitation ID |','| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',f"| SRC-ARXIV | 2026-05-15T09:00:00+08:00 | 2026-05-16T09:00:00+08:00 | 2026-09-01T20:00:00+08:00 | DataCite v2 00..99 + 542/542 semantic replay + official exact-v1 | checked | {len(rows)} | {';'.join(x['source_family_id'] for x in ret)} | pages=300;final_cursor=end;raw={D['raw_snapshot_records']};registered={len(rows)};screened={len(rows)};retained={len(ret)};closure={len(clo)} | 2026-05-16T00:59:59Z | screening-ledger-final.json#sha256={sha} | GAP-20260516-INDEPENDENT-AUDIT |",'', '### Coverage Limitations','',f'<!-- coverage:SRC-ARXIV:20260516:start -->author 已完成 {len(rows)}/{len(rows)}；非作者 false-positive/negative audit 尚未执行。<!-- coverage:SRC-ARXIV:20260516:end -->','','## 2. Candidate Ledger','','<!-- validator:candidate-ledger-v2.1 -->','| Source Family ID | Primary Identifier | Event Identity | Owner Week | First-public Date | Supporting Source IDs | Design Delta | System Reach | Durability | Total | Candidate State | Review Status | Access Status | Review Override | Review Ref | Owner Report Ref | Prior Review Ref | Reconciliation | Stable Node ID | Books Disposition | Books Review Ref | Benchmark Claim |','| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
for x in ret:
 a=x['arxiv_id'];s=x['score_v2'];sf=x['source_family_id'];o='knowledge_gap' if x['integration_disposition']=='Integrate' else 'none';L.append(f"| {sf} | arXiv:{a}v1 | paper-v1:{a} | 2026-W20 | 2026-05-15 | SRC-ARXIV | {s['design_delta']} | {s['system_reach']} | {s['durability']} | {s['total']} | retained | deep_complete | accessible | {o} | review:{sf} | self | — | new_in_window | {x['owner_node']} | {x['integration_disposition']} | books-review:{sf} | no |")
L += ['','## 3. Review Completion Receipt','','<!-- validator:review-completion-v1 -->','| Source Family ID | Review Provenance ID | Review Route | Primary Evidence Version | Reviewed Evidence Versions | Method / Identity Locators | Evaluation Locators | Limitations / Counterevidence Locators | Artifact Locators | Claim Boundary Ref | Completion Result |','| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |']
for x in ret:
 a=x['arxiv_id'];sf=x['source_family_id'];L.append(f'| {sf} | RP-TODO-{sf} | deep | arXiv:{a}v1 | SRC-ARXIV@arXiv:{a}v1 | arXiv:{a}v1 HTML — §Method / System Design | arXiv:{a}v1 HTML — §Experiments / Evaluation | arXiv:{a}v1 HTML — §Limitations / Discussion | arXiv:{a}v1 artifact; immutable commit Not Disclosed | claim:{sf} | complete |')
L += ['','### Source Reviews','']
for x in ret:
 a=x['arxiv_id'];sf=x['source_family_id'];L += [f'<!-- review:{sf}:start -->',f'#### {x["title"]}','',f'问题与机制：{x["screening_reason"]}。owner=`{x["owner_node"]}`。',f'全文定位：official `arXiv:{a}v1` Method、evaluation、limitations/discussion。',f'<!-- claim:{sf}:start -->只支持 exact-v1 披露的 workload、model、hardware、precision、length、batch、concurrency、SLO 与 evaluator；未披露为 Not Disclosed，不外推生产通用优势。<!-- claim:{sf}:end -->',f'Books Decision=`{x["integration_disposition"]}`；author decision 待非作者 current-Books challenge。',f'<!-- review:{sf}:end -->','']
L += ['## 4. Benchmark Contracts','','<!-- validator:benchmark-contract-v1 -->','| Source Family ID | Workload | Model | Hardware | Precision | Input Length | Output Length | Batch | Concurrency | SLO | Evaluator |','| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |','','## 5. Deep Analysis Selection','','<!-- validator:deep-analysis-selection-v1 -->','| Source Family ID | Eligibility | Decision | Analysis Unit ID | Subsumed By | Priority Rationale | Narrative Ref |','| --- | --- | --- | --- | --- | --- | --- |']
for x in ret:
 a=x['arxiv_id'];sf=x['source_family_id'];sel=a in DEEP;u=DEEP.get(a,'—');elig='score_7_9'+('; forced_review; potential_books_delta' if x['integration_disposition']=='Integrate' else '');L.append(f"| {sf} | {elig} | {'selected' if sel else 'not_selected'} | {u} | — | {'跨层 ownership pressure' if sel else 'full Review complete; owner-local delta'} | {'analysis:'+u if sel else 'analysis-decision:'+sf} |")
for a,u in DEEP.items(): L += ['',f'<!-- analysis:{u}:start -->',f'### {u}', '',f'{next(x for x in ret if x["arxiv_id"]==a)["screening_reason"]}。旧路径在固定 workload 下仍合理；新机制以额外状态、控制器误差和运维成本换取新的系统能力，越出 exact-v1 条件时回退旧路径。',f'<!-- analysis:{u}:end -->']
for x in ret:
 if x['arxiv_id'] not in DEEP:L.append(f'<!-- analysis-decision:{x["source_family_id"]}:start -->exact-v1 已审；未扩写只因 Daily 最多三项，不影响 Evidence/Books Decision。<!-- analysis-decision:{x["source_family_id"]}:end -->')
L += ['','## 6. Books Comparison','','<!-- validator:books-comparison-v1 -->','| Source Family ID | Stable Node ID | Target Chapter Ref | Adjacent Chapter Refs | Existing Proposition | New Evidence Delta | Evolution Relation | Decision | Books Review Ref |','| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
def cref(p):
 m=re.match(r'(\d+)-',Path(p).name);return f'{p}#chapter-{int(m.group(1))}' if m else f'{p}#knowledge-tree'
for x in ret:
 c=cb[x['arxiv_id']];sf=x['source_family_id'];L.append(f"| {sf} | {x['owner_node']} | {cref(c['owner_path'])} | {';'.join(cref(p) for p in c['adjacent_paths']) or cref(c['owner_path'])} | existing:{sf} | delta:{sf} | Direct Evolution | {x['integration_disposition']} | books-review:{sf} |")
for x in ret:
 c=cb[x['arxiv_id']];sf=x['source_family_id'];L += [f'<!-- books-review:{sf}:start -->',f'<!-- existing:{sf}:start -->{c["existing_proposition"]}<!-- existing:{sf}:end -->',f'<!-- delta:{sf}:start -->{c["new_evidence_delta"]}<!-- delta:{sf}:end --> Author decision=`{x["integration_disposition"]}`。',f'<!-- books-review:{sf}:end -->']
f0=ret[0]['source_family_id'];L += ['','## 7. Semantic Audit','','<!-- validator:semantic-audit-v1 -->','| Audit ID | Auditor | Scope | Reviewed Refs | Findings | Resolution | Status |','| --- | --- | --- | --- | --- | --- | --- |',f'| SA-20260516-COVERAGE | fresh-context:pending | coverage | coverage:SRC-ARXIV:20260516 | independent replay pending | non-author replays 542/542 | open |',f'| SA-20260516-EVIDENCE | fresh-context:pending | evidence | review:{f0} | exact-v1 claim challenge pending | non-author rechecks {len(ret)} | open |',f'| SA-20260516-SELECTION | fresh-context:pending | deep_analysis_selection | analysis:DA-SDC-SENSOR | Top3 challenge pending | non-author selection audit | open |',f'| SA-20260516-BOOKS | fresh-context:pending | books | books-review:{f0} | provisional queue pending | non-author current owner+adjacent compare | open |','','## 8. Ignored Noise','',f'{len(clo)} family-specific closures 保存在 screening ledger。','','## 9. Recommended Action','',f'非作者重放 542/542、挑战 {len(ret)} denominator 与 {len(queue)} provisional Integrate；随后 root 串行写回。','','## 10. Repository Changes','','- 新增 05-16 date-local author packet；未修改共享 Books。','- 未 stage、commit 或 push。','','## 11. Open Questions','','- 独立 reviewer 是否恢复 false negative 或收紧 provisional Integrate？','','<!-- validator:materials-request-v1 -->','| Request ID | Priority | Source Family ID | Source ID | Gap / Limitation ID | Owner Week | Known Identifiers / URLs | Missing Material | Why Existing Evidence Is Insufficient | Acceptable Substitute | Suggested File Name | Required Review Scope |','| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |','','## 12. Sources','']
for x in ret:L.append(f'- [{x["title"]}](https://arxiv.org/html/{x["arxiv_id"]}v1) — arXiv:{x["arxiv_id"]}v1；first-public 2026-05-15；accessed 2026-09-01')
L += ['','## 13. Final Status','','Completion Status: `In Progress`','','Coverage: `Open`','','Evidence: `Open`','','Books: `Open`','','unresolved findings: 4','','Author packet 完成；独立审计、root Books writeback 与 post-write audit 尚未完成。']
out=R/'papers/2026/05/16/README.md';out.parent.mkdir(parents=True,exist_ok=True);text='\n'.join(L)
for x in ret:
 sf=x['source_family_id'];a=x['arxiv_id'];b=text.split(f'<!-- review:{sf}:start -->',1)[1].split(f'<!-- review:{sf}:end -->',1)[0];cand={'Event Identity':f'paper-v1:{a}','Primary Identifier':f'arXiv:{a}v1','Supporting Source IDs':'SRC-ARXIV','Review Override':'knowledge_gap' if x['integration_disposition']=='Integrate' else 'none'};rp=_expected_review_provenance(sf,cand,'deep',f'arXiv:{a}v1',f'SRC-ARXIV@arXiv:{a}v1',f'arXiv:{a}v1 HTML — §Method / System Design',f'arXiv:{a}v1 HTML — §Experiments / Evaluation',f'arXiv:{a}v1 HTML — §Limitations / Discussion',f'arXiv:{a}v1 artifact; immutable commit Not Disclosed',f'claim:{sf}',f'review:{sf}',_normalized_body_sha256(b));text=text.replace('RP-TODO-'+sf,rp)
out.write_text(text+'\n');print(json.dumps({'raw':D['raw_snapshot_records'],'registered':len(rows),'screened':len(rows),'retained':len(ret),'closures':len(clo),'reviewed':len(ret),'blocked':0,'integrate_queue':len(queue)}))
