#!/usr/bin/env python3
"""Source-specific exact-v1 evidence map for the 2026-06-22 Daily.

This module is data only.  It does not write Daily, Books or shared state.
Every locator names an actual section or unique exact-v1 anchor; a conclusion
locator is used only when the manuscript has no dedicated limitations section.
"""

ND = "Not Disclosed"


def row(delta, method, evaluation, limitation, proof, boundary, workload,
        evaluator, disposition="Integrate", model=ND, hardware=ND,
        precision=ND, input_length=ND, output_length=ND, batch=ND,
        concurrency=ND, slo=ND, artifact=ND):
    return locals()


C = {
    "2606.22311": row(
        "把 privacy claim 从运行时猜测改成组件不可组装的结构性质：只有当暴露组件在既定组合规则下仍无法计算敏感谓词，系统才可声称 non-assembly；硬件隔离、阈值与允许组合必须进入证明身份。",
        "§3 Architecture; §4 Formal Properties; Birthmark Standard",
        "§6 Evaluation and Case Analysis; Appendix A",
        "§7.3 Limitations; §8 Conclusion",
        "在论文定义的 bounded predicate、组件暴露与组合规则下给出计算安全论证；证明不覆盖场景真值、任意 side channel 或被攻陷硬件。",
        "这是 computational、predicate-specific 保证，不是 information-theoretic secrecy；组合规则、birthmark threshold 或硬件信任根变化都会使证明失效。",
        "component-exposure privacy architecture", "formal non-assembly property and bounded attack analysis",
        hardware="trusted component/isolation assumptions disclosed in the manuscript",
        artifact="exact-title author manuscript mirror bound to arXiv:2606.22311v1"),
    "2606.22319": row(
        "把超声机器人控制拆成慢速语义规划、快速实时控制与独立 safety shield；高层 reasoning 只提议目标，低层 controller 与 shield 持有物理提交权。",
        "§III Methods: Slow Brain; Fast Brain; Safety Shield; Training and Inference Protocol",
        "§IV Experiments", "§V Conclusion and clinical-simulation scope",
        "仿真/受控超声任务显示分层控制可兼顾任务判断与控制频率。",
        "证据不覆盖真实临床部署、不同机器人/传感器校准或 safety shield 本身失效；因此不新增 Books delta。",
        "robotic ultrasound manipulation", "task success, control quality and safety violations",
        disposition="No Change — Existing Coverage"),
    "2606.22325": row(
        "把 MoE collapse 从单一 load-balance 指标提升为 routing dynamics：多种平衡正则最终可进入相似退化吸引域，必须同时观察 expert specialization、token flow 与训练阶段。",
        "§2 Problem Setup; §3 Routing Dynamics and Collapse Analysis",
        "§4 Experiments; §5 Ablations", "§6 Limitations",
        "受测 MoE 设置中，不同 routing/balance 路径出现共同 collapse pattern，并用训练轨迹与消融定位。",
        "结论受模型规模、数据和 router family 限制；观测到共同吸引域不证明所有 MoE 必然 collapse。",
        "Mixture-of-Experts training and routing", "loss, routing entropy, load, specialization and downstream quality"),
    "2606.22327": row(
        "把 online LLM scheduling 建模为带几何长度/剩余工作量的 admission 与排队问题；scheduler 以 workload shape 和 SLO slack 决定队列而非只按到达顺序。",
        "§3 Geometry-Aware Online Scheduling; theoretical bound and system design",
        "§4.1 Evaluation; §4 Experiments", "§5 Discussion and Conclusion",
        "在 8×A100-80GB、Llama-3.1-8B/70B、65,536 context 与 4,096 max generation 的受控负载上比较 mean/P95 per-token latency 与 throughput。",
        "作者 workload、FP16/BF16、QPS 2–128 与队列模型不能外推到其他 engine、KV tier 或多租户优先级；估计失准需要保守 admission fallback。",
        "online LLM serving over LMSYS-Chat and LongBench", "mean/P95 per-token latency and throughput",
        model="Llama-3.1-8B and Llama-3.1-70B", hardware="8 NVIDIA A100 80GB GPUs",
        precision="FP16/BF16", input_length="up to 65,536 tokens", output_length="up to 4,096 tokens",
        concurrency="2,000 requests; QPS in {2,8,16,32,64,128}", slo="reported mean/P95 per-token latency"),
    "2606.22329": row(
        "把 LLM-as-a-Judge 的可靠性拆成语言、轨迹阶段、模型与 rubric 条件，release gate 必须保存 judge identity 和 disagreement slice。",
        "§3 Methodology", "§5 Results", "§8 Limitations and Future Work",
        "跨语言和 agent trajectory 条件量化 judge 一致性、偏差与稳定性。",
        "benchmark 只能证明受测 judge/configuration；不能把 aggregate agreement 当成事实真值或跨语言 release authority。",
        "multilingual agent-trajectory judging", "agreement, reliability and bias slices",
        disposition="No Change — Existing Coverage"),
    "2606.22330": row(
        "把 skill optimization 拆成 failure hypothesis、candidate edit、独立验证与 promotion；skill library 的写权限不由单次 outcome 直接获得。",
        "§3 Method", "§4 Experiments", "§5 Discussion and Conclusion",
        "在 ALFWorld 与 Qwen3 系列受测配置上比较 hypothesis-driven skill edits 的任务表现。",
        "单环境和少量模型不能证明跨工具/长周期 promotion；与 Books 既有 skill promotion contract 相同。",
        "agent skill optimization on ALFWorld", "task success and skill-update quality",
        disposition="No Change — Existing Coverage", model="Qwen3-8B, Qwen3.5-9B and Qwen3.6-27B"),
    "2606.22338": row(
        "把 robot memory 评估从静态问答改为干扰条件下的 construction、retention、retrieval 与 action-use 分离；memory result 必须绑定 interference identity。",
        "§3 The Benchmark; §4 Memory Systems", "§5 Results", "§6 Limitations",
        "受控 simulation 中比较 memory systems 在 interference 下的任务保持与使用。",
        "只评一个 released checkpoint/system、单 episode condition，未覆盖多 seed 和真实机器人；不能把 benchmark pass 外推为长期可靠记忆。",
        "robot memory under interference", "memory construction, retrieval and action success"),
    "2606.22363": row(
        "把 world-model video 的 physical-consistency evaluation 从 reference video 相似度拆为结构、接触与时序约束；reference-free score 只能作为 detector，不能成为环境真值。",
        "§2 Methods", "§3 Experiments", "Limitation paragraph; §4 Conclusion",
        "在 OpenVLA 生成的五类任务、每任务 10×10 trials 上评估 reference-free physical consistency。",
        "指标会漏掉严重结构不一致与 non-contact failure，且未验证 OpenVLA 之外泛化；必须保留真实 environment transition adjudication。",
        "world-model-generated robot video", "reference-free physical-consistency metrics",
        model="OpenVLA", batch="five tasks; 10×10 trials per task"),
    "2606.22370": row(
        "长视频生成不能无限复制完整历史 KV；按 prompt-history 相关性选择可读历史，把 cache budget、selection error 与 continuity 绑定同一运行时状态。",
        "§3 Method", "§4 Experiments", "§5 Conclusion and long-single-shot scope",
        "30 秒 single-shot video 与 VBench 条件下比较 selective history KV 对连续性、质量和资源的影响。",
        "只覆盖受测长单镜头生成；selection miss 会破坏长期一致性，不能外推到可交互 world state。",
        "long single-shot video generation", "VBench quality, temporal consistency and memory cost",
        input_length="prompt plus selected history KV", output_length="30-second single-shot video"),
    "2606.22413": row(
        "把 AI 代码从一次生成/测试升级为 requirement→Java→formal model→多 verifier→结构化修复的闭环；LLM 只起草，proof tool 持有证据提交权。",
        "§3 Approach; §3.1 Top-Down Code Synthesis; §3.2 Extraction and Verification Phases; §3.3 Closed-Loop Refinement",
        "§4 Feasibility Demonstration; §4.2 Setup; §4.5 RQ3; §4.7 RQ5",
        "§5.4 Generalisability; §5.5 Trust Boundary; §5.6 Threats to Validity",
        "三个外部 safety-controller case、15/15 loop runs 收敛；cold 0/30，compile-only ablation 均未达到 formal verification。",
        "只证明 extraction-tractable Java profile 与三 case；formal model faithful extraction、spec completeness 和 verifier trust base 仍是边界。",
        "LLM-generated safety-critical Java", "Dafny/FDR4/Isabelle verification and convergence",
        model="Claude Code generation agent", batch="three case studies; five independent runs each",
        artifact="https://github.com/wrwei/Forge"),
    "2606.22419": row(
        "RAG/KG grounding 的收益取决于事实是否真的超出训练知识；index 命中不等于新增知识，必须分开 in-training、out-of-training 和 private-graph 条件。",
        "§5 Method: grounding over samyama-graph", "§6 Experiments", "§9 Limitations and Honest Negatives",
        "public PrimeKG 条件没有稳定 lift，synthetic out-of-training facts 显著受益，hybrid 条件介于两者。",
        "synthetic novel facts 不代表真实 private graph；grader/domain 也有限制；Books 已有 missing-knowledge boundary。",
        "clinical QA with public, synthetic-new and hybrid graph knowledge", "answer accuracy and grounding contribution",
        disposition="No Change — Existing Coverage"),
    "2606.22470": row(
        "把 prompt 冲突评估从答案对错拆为冲突类型与行为标签，显式记录模型 follow-A/follow-B/both/neither，而不是假定一条隐藏优先级总能解决。",
        "§III Dataset Construction; §IV PRIME Framework", "§V Experimental Design; §VI Results", "§VII Discussion; §VIII Conclusions",
        "72 source instructions、216 contradictory prompts，覆盖 reasoning/length/format conflict 与多模型行为分布。",
        "人工构造的三类冲突不能覆盖 system/developer/tool 权限层级或安全攻击；Books 已拥有 prompt authority contract。",
        "incompatible prompt instructions", "deterministic behavioral labels and statistical analysis",
        disposition="No Change — Existing Coverage", batch="72 source instructions; 216 contradictory prompts"),
    "2606.22474": row(
        "把 factual verification 从所有 claim 同成本复核改为 claim-risk/uncertainty 驱动的资源分配；阈值、coverage 与 verification latency 必须联合验收。",
        "§3 FACTOR Method", "§4 Experiments", "§5 Limitations and Conclusion",
        "在 50 篇 biography、四候选生成条件上比较 adaptive verification 的 factuality 与成本。",
        "March-2022 Wikipedia、FactScore 和 T4/256-token 生成条件限定结论；uncertainty score 未校准时不能拥有 release authority。",
        "adaptive claim verification for long-form biography generation", "FactScore, verification coverage and latency",
        hardware="Kaggle NVIDIA T4 16GB", input_length="biography prompt", output_length="80–256 new tokens",
        batch="four candidates per prompt"),
    "2606.22485": row(
        "把 agent reasoning workflow 编译成可重放的 logical trace：tool invocation、synthesized rule 与 derived fact 都成为确定性 program，而非只保存在对话上下文。",
        "§4 VADAOrchestra: System Architecture; §4.2 Orchestration Pipeline; §4.3 Logical Trace",
        "§5 Experimental Evaluation", "§6 Conclusion and financial-use-case boundary",
        "在匿名 financial ownership/concentration 问答上比较 LLM-only、knowledge-enhanced 与可重放 logical trace。",
        "受测金融数据和 Vadalog rules 不证明任意工具或实时数据正确；规则错误可被确定性重放但不会自动被纠正。",
        "adaptive reasoning over financial relational data", "exact match, LLM-as-judge and trace reproducibility",
        model="Llama-3.3-70B-Instruct and GPT-4o"),
    "2606.22488": row(
        "开放环境 planning 需要把符号 world state 作为可演进、可修订 artifact，并把 observation→symbol update→plan→execution feedback 分开。",
        "§3 Method", "§4 Experiments", "Appendix A Limitations and Future Discussions",
        "受测开放环境任务显示 evolving symbolic world 可支持更长 planning 与修订。",
        "symbol extraction 和 transition update 仍可错，environment coverage 受限；不能把 symbolic state 当作真实环境。",
        "planning in open-ended environments", "task success, planning quality and world-state update quality"),
    "2606.22504": row(
        "把 agent authority 从 task-wide tool visibility 改为 resource/effect/phase scoped capability：grant 生成 epoch-bound handle，trusted closure 后从下一 planner interface 移除，并在 effect 前拒绝 stale replay。",
        "§3 Problem and Threat Model; §4 Model of Capabilities and Interfaces; §5 Portico as a Reference Monitor",
        "§6 Experimental Questions and Setup; §7 Results", "§8 Discussion: Revocation Scope and External Validity",
        "受控 suites 与八个 pinned Python repositories 比较 all-visible、non-revoking、coarse action filter 和 Portico；Portico 保持 scope 且阻止 stale effect。",
        "依赖 mediated tools、sound typed catalog 与 linearizable effect-time recheck；不覆盖 bypass shell/network、compromised host 或所有工具生态。",
        "revocable coding-agent resource/effect capabilities", "task success, scope, execution violations and stale-effect replay",
        model="frozen Hugging Face router trace plus GPT-5.5, Gemini 3.5 Flash and Claude Opus 4.8 slice",
        batch="controlled lifecycle suites plus 8 pinned Python repositories",
        artifact="Not Disclosed — exact-v1 manuscript names Portico MCP/tool artifacts but this review did not use a stable public artifact locator"),
    "2606.22509": row(
        "在 hierarchical RL 执行动作前，用 world model 想象候选 transition 并以 safety constraint 过滤；world model 只提议风险，真实 controller 和 fallback 持有提交权。",
        "§3 ITES Method; §4 Hierarchical Safety Integration", "§5 Experiments", "§6 Limitations and Conclusion",
        "五个 seed 的受控 HRL 任务显示 imagined-transition screening 可降低不安全执行。",
        "手工 goal mapping、RTX3060 8GB 实验与模拟环境不能外推真实机器人或视觉泛化；model error 会产生 false-safe。",
        "long-horizon safe hierarchical reinforcement learning", "return, safety violations and planning success",
        hardware="NVIDIA RTX 3060 8GB", batch="5 random seeds"),
    "2606.22528": row(
        "把 context compaction 识别为治理控制面：安全约束、授权与 provenance 在压缩后必须由 constraint pinning/typed state 继续存在，不能依赖普通 summary 自然保留。",
        "§3 Compaction-Eviction Attack; §4 Constraint Pinning", "§5 Results and Robustness", "§6 Limitations",
        "重复 compaction、跨语言和多模型条件显示 governance instruction 可被逐步挤出；pinning 降低该 failure。",
        "攻击/防护受具体 compactor 与提示结构限制；pinning 不保证约束本身正确，也不替代 effect-time reference monitor。",
        "long-horizon agents under repeated context compaction", "constraint retention, unsafe action rate and attack success"),
    "2606.22541": row(
        "MoE prefill 不应把 attention、expert dispatch 与 communication 绑成同步 barrier；ASAP 以 PD disaggregation 和 asynchronous expert pipeline 重排控制流，但必须保存请求/segment/expert state identity。",
        "§3 ASAP Design", "§5 Evaluation", "§6 Discussion and Conclusion",
        "CloudMatrix384 上用 DeepSeek-V3.2、D4/T4/E16 的 32 NPU 设置，在 8K/device sequence、batch up to 32K 下报告 90% SLO-compliant throughput。",
        "结论绑定 CANN8.3、PyTorch2.1、特定 MoE/硬件与 workload；异步 stale/misroute 或 SLO slack 耗尽时必须退回同步/隔离路径。",
        "disaggregated asynchronous MoE prefill", "TTFT and SLO-compliant throughput",
        model="DeepSeek-V3.2", hardware="CloudMatrix384; 32 NPUs at D=4/T=4/E=16",
        precision=ND, input_length="up to 8K tokens per device; longer requests use separate sequence parallelism",
        batch="up to 32K tokens", slo="TTFT and throughput SLO",
        artifact="Not Disclosed — exact-v1 manuscript describes the PyTorch 2.1/CANN 8.3 implementation but this review did not use a stable public artifact locator"),
    "2606.22560": row(
        "第三方 LLM gateway 不能仅返回 provider name；每次路径选择要生成 evidence-bound provenance，绑定 policy、provider endpoint、fallback、请求版本与可验证 receipt。",
        "§3 Provenance Model; §4 Gateway-Path Binding; §5 Implementation", "§7 Evaluation", "§9 Limitations and Conclusion",
        "原型评估验证 receipt 可区分实际 gateway path，并测量额外开销。",
        "只覆盖受测 gateway/provider；receipt 证明公开路径与策略执行，不证明 provider 内部模型或隐藏处理。",
        "third-party LLM inference gateway", "provenance completeness, tamper detection and overhead"),
    "2606.22565": row(
        "多模态 CoT 的收益瓶颈常在视觉 representation 而非文字 reasoning 长度；系统要分开 visual extraction、reasoning token 与最终 task evidence。",
        "§2 Problem Formulation; §3 Strengths and Pitfalls; §4 Shallow Visual Reflection",
        "§5 Experiments", "§Limitations",
        "12 tasks、14 non-reasoning 与 8 reasoning models 显示 CoT 收益高度任务依赖，视觉 bottleneck 不会由更长文字普遍修复。",
        "benchmark/model slice 不证明所有 modality；reasoning trace 也不等于因果使用的视觉证据。",
        "multimodal reasoning across 12 tasks", "task accuracy and visual-reasoning diagnostics",
        batch="12 tasks; 22 models"),
    "2606.22570": row(
        "LLM reasoning RL 的 update quality 取决于 rollout freshness、update count 与 policy drift；同一 reward 下不能把更多 optimizer steps 当成免费收益。",
        "§3 Analysis of Update Factors; §4 Algorithm", "§5 Experiments", "Appendix N Limitations",
        "Qwen2.5-7B、Numina-like reasoning workload 中比较 near-on-policy 2 updates/rollout 与 off-policy 16 updates，并做关键因素消融。",
        "单模型/任务与固定 1e-6 LR 不证明通用最优 update ratio；更少 drift 以额外 rollout 成本为代价。",
        "RL for LLM mathematical reasoning", "reward, accuracy, KL/policy drift and sample efficiency",
        model="Qwen2.5-7B", input_length="1,024 tokens", output_length="3,072 tokens",
        batch="training batch 128/256", slo="2 versus 16 updates per rollout"),
    "2606.22593": row(
        "registry 的 release authority 不是 package presence；必须测量谁能发布、撤回、覆盖 metadata，以及 registry mediator 是否保留身份和审计链。",
        "§3 Authority Model and Measurement; §3.4 Evaluation", "§4 Results", "§5 Limitations and Discussion",
        "跨 package ecosystems 测量 registry-mediated release authority 与 ownership/maintenance exposure。",
        "公开 registry metadata 只能观察可见 authority，不证明离线凭据、组织流程或未披露 compromise。",
        "registry-mediated package ecosystems", "release-authority exposure and ownership metrics"),
    "2606.22600": row(
        "on-policy distillation 的 token position 并非等权：teacher/student prefix compatibility 与序列位置共同影响 gradient；修正 bias 必须声明 density proxy 和残余 mismatch。",
        "§3 Position-Bias Analysis; §4 Proposed Correction", "§5 Experiments; Appendix C Protocol", "Appendix E Limitations",
        "Qwen3-4B student/teacher 条件比较 DPO/OPD，并量化 position bias 与 correction。",
        "prefix compatibility 只是 density correction proxy；4B scale、数据与 DPO 小 10× LR/少 40× rows 构成 confound。",
        "on-policy distillation for language reasoning", "quality, position-wise gradients and bias diagnostics",
        model="Qwen3-4B student and teacher configurations"),
    "2606.22610": row(
        "autonomous research workflow 必须把 hypothesis、main-result contract、job identity、event log 与 human refinement 变成持久 artifact；启动 job 不等于研究闭环。",
        "§3 PaperClaw Architecture and Lifecycle", "§4 Experiments", "§5 Conclusion and Future Work",
        "系统展示从 IDEA.md、hypothesis map、detached monitored job 到 result artifact 的 research lifecycle。",
        "作者明确 fully closed-loop learning 仍是 future work；案例不能证明无人监督研究正确性，Books 已有同一 workflow contract。",
        "agentic research lifecycle", "artifact completeness and task outcomes",
        disposition="No Change — Existing Coverage"),
    "2606.22613": row(
        "agent evaluation 不能只跑固定 suite；SkillAudit 以 skill identity、coverage、probe 与 observed capability gap 组织 assessment。",
        "§3 SkillAudit Framework", "§5 Empirical Evaluation", "§Conclusion and Limitations",
        "226 public skills、少量 agent/model configs 上比较 fixed-suite 与 skill-centered assessment。",
        "scanner/probe coverage、单 matched run 和小配置限制结论；不能把未命中当不存在。",
        "skill-centered agent assessment", "skill coverage, probe findings and task outcomes",
        disposition="No Change — Existing Coverage", batch="226 public skills; single matched runs"),
    "2606.22633": row(
        "把 verbal confidence 与内部冲突分开：模型可高置信输出但隐藏 state 对相反命题均有支持，evaluation 需要独立测 conflict geometry 和 resolution behavior。",
        "§2 Method", "§3 Experiments and Results", "§Limitations",
        "受测模型/任务上内部 uncertainty 与最终置信可解耦，并比较 conflict resolution。",
        "representation probe 是诊断，不证明因果使用；不能直接成为 release gate。",
        "LLM cognitive-conflict and uncertainty evaluation", "internal conflict probes, confidence and answer accuracy"),
    "2606.22659": row(
        "prompt-injection detector 的 calibration 要按 attack severity 与 shift slice，而不是 pooled ECE；frozen threshold 必须显示 confident false-negative risk。",
        "§3 Method", "§4 Results", "§5 Discussion and Bounded Scope",
        "ProtectAI-v2 与 Prompt-Guard-2 在 direct/indirect/jailbreak/over-defense 数据上比较 attack-conditional severity calibration，并用 Qwen targets 检查 downstream effect。",
        "pooled calibration 会隐藏严重攻击 false negative；512-token detector 与受测数据/4-bit targets 不能外推所有 tool agent。",
        "prompt-injection detection under attack shift", "severity-aware calibration, false negatives and downstream attack success",
        model="ProtectAI-v2; Prompt-Guard-2 86M/22M; Qwen2.5-7B/3B targets",
        precision="Qwen targets at 4-bit", input_length="512 detector tokens", artifact="official arXiv:2606.22659v1 PDF"),
    "2606.22673": row(
        "mechanistic safety steering 应把 discovered subspace、intervention strength 与 multi-turn outcome 分开；解释性方向不能自动取得生产 policy 权限。",
        "§3 AgentLens Method", "§4 Experiments; §5 Results", "§6 Discussion and Benchmark Scope",
        "Llama-3.1-8B、Qwen2.5-7B、Gemma-2-9B 在 multi-turn coding safety testbed 上测 steering 与 interpretation。",
        "8×A100-40GB 的初始 testbed 不覆盖完整 malicious workflow，subspace 也可能随模型/任务漂移；Books 已有受限 steering boundary。",
        "multi-turn coding-agent safety steering", "safety, utility and subspace interpretability",
        disposition="No Change — Existing Coverage", model="Llama-3.1-8B, Qwen2.5-7B and Gemma-2-9B",
        hardware="8 NVIDIA A100 40GB GPUs"),
    "2606.22678": row(
        "coding-agent evaluation 要测工程过程纪律：plan、test、review、rollback 与 artifact hygiene，最终 patch pass 不能覆盖危险中间过程。",
        "§3 RigorBench Design; §4 Process Rubric", "§5 Evaluation", "§VIII Limitations",
        "受测 coding agents 上以 process-aware rubric 比较最终结果与工程过程。",
        "rubric/judge 仍可能偏差且仓库任务有限；Books 已有 process evidence contract。",
        "autonomous coding-agent engineering process", "process compliance, patch quality and task success",
        disposition="No Change — Existing Coverage"),
    "2606.22698": row(
        "black-box agent forensics 需要固定 probe transcript、system-prompt/topic 条件与 attribution threshold，把模型/配置 fingerprint 当 evidence 而非身份真值。",
        "§3 Approach", "§4 Experiments; §4.3 Evaluation", "§7 Limitations",
        "240K synthetic transcripts、6 base models、40 system prompts、70 topics 上训练/评估 attribution detective。",
        "synthetic transcript 与 threshold/config scope 限制外推；provider 更新、sampling 和 prompt drift 会使 fingerprint 失效。",
        "conversational-agent black-box attribution", "model/config attribution accuracy and robustness",
        model="six base models; Qwen-4B detective", batch="240K transcripts; 40 system prompts; 70 topics"),
    "2606.22704": row(
        "patch backport workflow 要把 candidate patch、dependency/version、test oracle、semantic verification 与 human escalation 串成可回滚状态机。",
        "§III VeriPort System and Workflow", "§V-A Experimental Setup; §V Evaluation", "§V-E Limitations",
        "BackportBench 202 tasks/12 repos/3 ecosystems 与 CVEPatchBench 上评估自动 backport 和验证。",
        "benchmark tests 不证明所有语义等价或供应链安全；无法验证时应保留人工 adjudication。",
        "verified patch backporting", "backport success, test/semantic verification and cost",
        batch="202 tasks across 12 repositories and 3 ecosystems plus CVEPatchBench"),
    "2606.22716": row(
        "效率 RL 不应奖励所有短答案；correct-only adaptive reward 先冻结 correctness，再在正确轨迹中调节效率 credit，避免把错误的短输出当优化方向。",
        "§3 Method and Reward Formalism", "§3.3 Experimental Setup; §4 Results", "§Limitations",
        "Qwen3-1.7B、NuminaMath-TIR、GRPO group 16、1200 steps 条件比较效率和 correctness。",
        "单 scale/数据与 reward verifier 限制结论；correct-only gate 会牺牲错误样本中的潜在学习信号。",
        "GRPO reasoning-efficiency training", "accuracy, response length, reward stability and efficiency",
        model="Qwen3-1.7B", batch="GRPO group size 16; 1,200 steps"),
    "2606.22719": row(
        "forecast benchmark 必须按 decision-time 可获得输入冻结，并以 walk-forward 防止 later-data leakage；nowcast revision 也要成为 dataset version。",
        "§3 Method", "§4 Results", "§5 Discussion — Limitations",
        "Qwen2.5-7B-Instruct 4-bit NF4、36 monthly decisions 上评估 macro factor ranking；置信区间含零且 permutation p=0.11。",
        "样本小、统计功效不足且金融 domain 特定；结果不能证明生产 alpha，只证明 leakage-aware protocol。",
        "real-time macroeconomic nowcast ranking", "walk-forward ranking return and statistical uncertainty",
        model="Qwen2.5-7B-Instruct", precision="4-bit NF4", batch="36 monthly decisions"),
    "2606.22729": row(
        "action-only diffusion policy 可在 inference 时由 world model 预测 state，再用 temporal-logic robustness 引导采样；guidance 只约束候选，真实 observation 和 controller 保留提交权。",
        "§II Method", "§III Experiments", "§IV Limitations and Conclusion",
        "受控 simulation 展示 STL guidance 改善 action-only policy 的 constraint satisfaction。",
        "world-model error 会让 temporal formula 对错误 state 成立；短论文/模拟结果不证明真实机器人 safety。",
        "action-only diffusion policies with temporal constraints", "task success and STL satisfaction"),
    "2606.22731": row(
        "自动研究必须分开 discovery 与 held-out certification：candidate idea 可由 agent 搜索，但只有冻结数据/评估合同的复测结果可 promotion。",
        "§3 Closed-loop Auto Research Method", "§4 Experiments", "§5 Conclusion and molecular-domain boundary",
        "在 molecular property prediction 上运行 discovery→implementation→held-out certification 闭环。",
        "单一分子领域与作者 harness 不证明跨科学任务自主研究；Books 已有 discovery/certification 分离。",
        "autonomous molecular-property research", "held-out predictive improvement and reproducibility",
        disposition="No Change — Existing Coverage"),
    "2606.22737": row(
        "stateful Agent evaluation 可由确定性 environment transition、predicate 与 event log 计算 GroundEval，而不是让 LLM judge 重新解释完整轨迹。",
        "§3 GroundEval Framework", "§5 Evaluation", "§10 Limitations",
        "受测 stateful tasks 中比较 deterministic tool/state mode 与 context-only mode 的 observability 和判定。",
        "context mode 可观测性更弱，确定性 evaluator 也只覆盖已编码 predicate；未编码目标不会自动出现。",
        "deterministic stateful-agent evaluation", "agreement, observability and evaluation reproducibility"),
    "2606.23740": row(
        "offline reasoning training 的方法差异要同时看 weight-space trajectory、data/step/LR matching 与功能结果；几何分离若训练预算不匹配不能归因于 objective。",
        "§2 Experimental Setup", "§3 Results", "§4 Discussion; Limitations",
        "Qwen3-4B-Instruct-2507、attention LoRA rank32/alpha64、BF16、1500 steps 对比训练轨迹。",
        "单 seed/domain/checkpoint，且 DPO 用 10× smaller LR 与 40× fewer rows，构成强 confound；不能形成 objective superiority 结论。",
        "offline reasoning training weight-space geometry", "weight-space distance, representation and reasoning accuracy",
        model="Qwen3-4B-Instruct-2507", precision="BF16; attention LoRA rank 32 alpha 64",
        batch="32; 1,500 steps"),
    "2606.23743": row(
        "video inference optimization 应把 graph transformation、kernel/execution plan、memory schedule 与 serving config 绑定同一可重建 artifact；agent 只能提出/搜索 plan，validator 才能提交。",
        "§3 Sol Architecture; §4 Agent-Native Optimization", "§5 Experiments", "§6 Limitations and Future Work",
        "三个 video-generation models 的作者配置报告超过 2× acceleration，并检查自动 plan。",
        "收益 instance-specific 于模型、硬件和 serving config，最终 visual quality 仍需人评；不能把单次搜索结果外推通用 engine。",
        "full-stack video-generation inference", "latency, throughput, memory and generation quality",
        model="three video-generation models named in exact-v1", slo="author-reported latency/throughput configuration"),
}


SELECTED = {
    "2606.22504": "DA-20260622-REVOCABLE-AUTHORITY",
    "2606.22528": "DA-20260622-COMPACTION-GOVERNANCE",
    "2606.22541": "DA-20260622-ASYNC-MOE-PREFILL",
}
