#!/usr/bin/env python3
"""Manually synthesized, paper-specific review notes for March lane A.

There is intentionally no default.  A retained family without an explicit
note must fail rendering instead of silently receiving template prose.
"""

NOTES = {
    "2603.00188": {
        "constraint": "长时程 GUI agent 的视觉轨迹会让 KV 状态持续膨胀；只按注意力或 recency 删除 token 会破坏动作轨迹中的空间连续性。",
        "mechanism": "ST-Lite 把视觉 token 的空间位置和交互轨迹共同用于训练外压缩，令保留决策拥有 GUI 轨迹语义，而不是只由通用 KV eviction 规则决定。",
        "evidence": "作者只在其 GUI-agent、压缩率与任务集合上比较性能和缓存开销；这支持该保留信号在该 workload 下有效，不证明它适用于普通文本或任意视觉 agent。",
        "tradeoff": "收益是降低长轨迹状态量；代价是额外轨迹特征与任务耦合，failure 是关键但低频的视觉状态被误删。短轨迹或显存宽裕时，全量 KV 仍更简单。",
    },
    "2603.00196": {
        "constraint": "云端 LLM 推理需要隐藏 prompt、权重和中间状态，但把整个 runtime 放进可信执行环境会扩大 TCB 并引入内存与性能压力。",
        "mechanism": "论文把 confidential inference 分解为隔离边界、远程证明、加密通道和可验证 runtime 组成，明确哪些请求状态由 enclave/guest、host 与客户端分别拥有。",
        "evidence": "实验只证明其原型配置下的隔离和开销；未证明云提供方所有 side channel 被消除，也未证明不同 GPU/TEE 组合具有同一性能。",
        "tradeoff": "机密性换来证明链、密钥生命周期和受限设备支持；failure 包括证明过期、I/O 泄露和 TCB 漏洞。可信私有集群仍可能比复杂 TEE 路径更合理。",
    },
    "2603.00349": {
        "constraint": "Multi-Agent 的最终成功率无法解释合作是否真实发生，也无法把自然语言计划、消息与环境状态变化对齐。",
        "mechanism": "COOP²/EmCoop 建立 cognitive-event 到 environment-step 的时间映射，并沿约束满足过程度量计划、通信和执行，使合作成为可观察 trace 而非结果标签。",
        "evidence": "作者在其 embodied task、拓扑和模型面板上展示多维合作指标；这证明指标能暴露不同协作轨迹，不证明存在跨任务唯一的 cooperation score。",
        "tradeoff": "可解释性换来更重的 trace instrumentation 与 task-specific constraint model；failure 是时钟或事件归因错误。只关心最终 SLA 的简单任务仍可用 outcome metric。",
    },
    "2603.00356": {
        "constraint": "多租户推理中，token 数不是只用于计费的结果量；prefill、decode、KV residency 与 deadline 让 token 成为调度前必须管理的资源单位。",
        "mechanism": "论文把 token budget、admission、运行中配额与 reclaim 连接起来，使平台在请求进入和执行期间都能控制 token 责任，而非只按 request count 排队。",
        "evidence": "作者评估其 workload 下的隔离、利用率与尾延迟；证据支持 token-aware policy 的局部收益，不证明同一策略跨模型、长度分布和硬件均占优。",
        "tradeoff": "更细粒度控制可降低 noisy-neighbor，但需要在线估算未来 token 与 KV 占用；低估会破坏 SLO，高估会浪费容量。稳定、同质 workload 仍可用简单队列。",
    },
    "2603.00381": {
        "constraint": "仅检查 Agent 消息的表面合规无法约束合谋信号，因为策略允许的多个表达仍可承载隐蔽选择。",
        "mechanism": "CLBC 将 generation 与 transcript admission 分离：消息只有携带绑定 policy、随机性、transcript chain 和字段约束的 proof envelope 并通过小 verifier 后才进入共享状态。",
        "evidence": "理论界限与实验只覆盖论文声明的 residual channels、catalog、模型和 attacker；不能把 leakage bound 外推到未纳入 predicate 的环境 side channel。",
        "tradeoff": "fail-closed admission 降低 covert capacity，但引入证明开销、predicate 版本治理与拒绝可用性风险；低风险协作或无需保密的通信仍可直接记录消息。",
    },
    "2603.00468": {
        "constraint": "静态 RCA benchmark 可复现但缺少工具交互，live testbed 真实却让每次事故证据漂移，二者都难审计 agent 的调查过程。",
        "mechanism": "Cloud-OpsBench 冻结日志、指标、配置和瞬时 data-plane 状态为 State Snapshot，再通过标准诊断接口回放，解耦状态保存与工具交互。",
        "evidence": "754 个案例、57 类故障和两个微服务 workload 支持其可复算比较；不证明 snapshot 覆盖生产事故中的所有时变因果或外部依赖。",
        "tradeoff": "可重放性换来捕获与维护成本，failure 是 snapshot 缺少关键状态而制造假确定性。需要实时恢复能力时仍要补 live drill。",
    },
    "2603.00495": {
        "constraint": "AI workload 同时包含模型执行、数据移动、隔离、可观测和控制面；把它当普通容器会丢失 accelerator 与 model-state contract。",
        "mechanism": "AI Runtime Infrastructure 将模型 artifact、执行计划、device runtime 和 platform control 分层，显式化跨层接口而不是把所有责任塞进框架。",
        "evidence": "论文的架构与案例证明这种责任分解可表达现有 runtime；没有统一 benchmark 证明其抽象在所有平台上最优。",
        "tradeoff": "清晰接口改善替换与治理，但增加版本兼容和跨层协调；小规模单框架部署仍可能不需要完整 runtime layer。",
    },
    "2603.00724": {
        "constraint": "多任务 RL 的稀疏、异质 reward 让单一手写奖励既难扩展又易产生 task-specific hacking。",
        "mechanism": "RLAR 使用 agentic reward system 分解任务、调用验证器并组合反馈，把 reward generation 变成可审计运行时而非一个静态 scalar function。",
        "evidence": "作者比较其任务集合中的训练与泛化结果；这支持 reward orchestration 的可用性，不证明自动 reward 永远忠实于真实目标。",
        "tradeoff": "覆盖更多任务的代价是 evaluator cost、误差相关与更大的攻击面；可形式验证任务仍应优先 deterministic reward。",
    },
    "2603.00811": {
        "constraint": "数据 curation 本身会暴露样本是否被选择；只保护训练后模型并不能隐藏过滤、去重或质量排序的成员信息。",
        "mechanism": "Curation Leaks 将攻击目标从 training membership 扩展到 selection membership，并沿 curator 输出和模型行为测量选择决策泄露。",
        "evidence": "攻击在作者的数据、curator 和 threat model 下成立；没有证明所有 curation pipeline 都同等泄露，也未给出完整生产缓解成本。",
        "tradeoff": "增强选择隐私可能降低可解释性、质量控制或增加随机化；公开数据流水线仍可优先透明性而非 selection secrecy。",
    },
    "2603.00825": {
        "constraint": "只预测下一 observation 的 world model 不足以训练行为 agent，因为环境演化必须受条件、动作与多步 rollout 约束。",
        "mechanism": "COMBAT 将 behavior/action condition 注入生成式 dynamics，使模拟状态转移能为 agent 产生可控训练轨迹。",
        "evidence": "作者实验支持其环境与行为任务下的 controllability；不证明生成质量等价于因果正确性或真实环境安全。",
        "tradeoff": "可控 rollout 提高训练覆盖，但会把 simulator bias 注入 policy；高风险动作仍需真实反馈与安全 envelope。",
    },
    "2603.01058": {
        "constraint": "MoE 推理的专家权重容量与不均匀路由使纯 GPU 部署受显存约束，而朴素 CPU offload 又受链路和计算差距限制。",
        "mechanism": "TriMoE 将活跃专家在 GPU、AMX CPU 与 DIMM-NDP 间分层放置并协调数据流，利用异构算力而非把 CPU 仅作存储。",
        "evidence": "吞吐结果绑定作者模型、路由分布和硬件原型；不证明 NDP 可得性、成本或任意专家热度下均有收益。",
        "tradeoff": "容量与吞吐换来 placement、prefetch 和一致性复杂度；链路拥塞或专家热度突变会反转收益。可装入 GPU 的小 MoE 仍应保持单层执行。",
    },
    "2603.01209": {
        "constraint": "Agent 训练若每个 episode 重置 interpreter，而部署保留进程、文件和缓存，policy 学到的是错误的 runtime semantics。",
        "mechanism": "论文把 interpreter persistence 作为训练环境状态的一部分，使跨 turn 的变量、artifact 与副作用与部署执行合同一致。",
        "evidence": "实验比较持久/非持久 runtime 下的 agent 行为；只证明所用 CodeAct 环境，不能外推所有工具和 sandbox。",
        "tradeoff": "语义对齐提高长任务能力，但扩大状态污染、泄密和不可复现风险；无跨步依赖的任务仍应使用 ephemeral execution。",
    },
    "2603.01399": {
        "constraint": "self-speculative decoding 需要 draft 足够便宜且 verification 保持准确；量化可降内存却可能降低接受率。",
        "mechanism": "Quasar 对 draft/self-draft 状态做量化并设计内存受限 verification，联合优化草稿成本与接受路径。",
        "evidence": "加速与质量只属于作者模型、量化格式、序列和硬件；没有证明跨模型校准或所有分布均保持 exactness。",
        "tradeoff": "更小草稿状态换来量化误差和额外校准；低接受率或短输出时普通 decode 更合适。",
    },
    "2603.01499": {
        "constraint": "隐私推理若只靠传输加密，服务端仍看到表示与计算；完全同态/TEE 又可能成本过高或改变信任假设。",
        "mechanism": "covariant obfuscation 通过保持所需变换关系的输入/权重表示来隐藏原值，使服务端在混淆域执行。",
        "evidence": "技术报告只在其攻击模型和任务中展示可用性；没有证明密码学级 indistinguishability 或覆盖 side channel。",
        "tradeoff": "较轻执行换来特定变换假设和可能的精度/泄露边界；强对手或合规场景仍需成熟密码学或可信硬件。",
    },
    "2603.01548": {
        "constraint": "Agent tool router 的静态映射在工具变更或错误累积时会持续失败，人工修复又无法跟上工具规模。",
        "mechanism": "论文将工具、能力和失败关系建图，并根据执行反馈修复路由边，使错误成为 routing-state 更新信号。",
        "evidence": "成本和成功率只覆盖作者工具集、错误注入和模型；不证明自动修复不会把偶发失败固化为错误拓扑。",
        "tradeoff": "自愈降低人工维护，但引入图状态漂移与反馈污染；小而稳定的工具集合仍适合显式映射。",
    },
    "2603.01581": {
        "constraint": "VLA 动作序列具有运动连续性，通用 token equality/概率接受规则会拒绝语义可行但数值不同的 draft。",
        "mechanism": "KERV 用运动学误差校正/接受 VLA 草稿，把 verification 从离散 token 一致扩展到受动作动力学约束的近似路径。",
        "evidence": "结果仅对所测 robot、动作表示和容差成立；不证明近似接受保持一般任务的 exact distribution。",
        "tradeoff": "更高接受率换来非精确语义和 safety threshold；对不可容忍动作误差的控制回路仍应精确验证。",
    },
    "2603.01661": {
        "constraint": "移动端 Agentic RAG 同时竞争 CPU/GPU/NPU、内存和能耗，固定算子放置无法适应检索与生成阶段变化。",
        "mechanism": "HeRo 根据阶段、热状态和设备能力动态编排检索、rerank 与生成，把异构 SoC 资源作为在线调度对象。",
        "evidence": "延迟/能耗结果绑定作者移动 SoC、模型和 RAG pipeline；不证明所有厂商 runtime 都支持同等迁移成本。",
        "tradeoff": "适应性提高利用率但增加 profiling、迁移与 thermal feedback；固定 workload 可用静态 placement 降复杂度。",
    },
    "2603.01960": {
        "constraint": "通用 SDPA kernel 在形状、mask 和 tile 边界上可能无法同时利用 CUDA memory hierarchy 与计算流水。",
        "mechanism": "TiledAttention 将 attention 分解为显式 CUDA tiles 并控制加载、累加与边界处理，令执行计划而非框架默认 kernel 拥有数据移动。",
        "evidence": "性能只属于给定 GPU、dtype、shape 和 PyTorch integration；不证明所有 attention 变体或未来硬件仍占优。",
        "tradeoff": "定制 kernel 换来形状特化、维护和数值验证成本；常规形状仍可依赖成熟 vendor kernel。",
    },
    "2603.01966": {
        "constraint": "长对话 memory benchmark 若只测最终回答，会混淆记忆写入、检索、更新与冲突处理。",
        "mechanism": "AMemGym 通过交互式长时程环境分别触发记忆生命周期操作，使 memory policy 在动态对话中被观察。",
        "evidence": "benchmark 揭示作者任务和模型中的失败模式；不证明其任务分布代表真实助手，也不提供唯一 memory quality 指标。",
        "tradeoff": "生命周期覆盖提高诊断性但增加标注与 evaluator 依赖；简单一次性 QA 不需要该复杂度。",
    },
    "2603.02075": {
        "constraint": "多模态训练数据样本的 decode、augment、长度和设备需求差异大，FIFO pipeline 会让某一 modality 阻塞整体 step。",
        "mechanism": "Trident 依据样本/模态 cost 动态调度数据处理阶段，在异构 worker 间平衡生产速度与 trainer 消费。",
        "evidence": "吞吐改善绑定作者数据组合、worker 和存储；不证明调度开销在小数据或单模态 workload 中值得。",
        "tradeoff": "减少 pipeline bubble 但引入 cost estimation、重排和数据顺序变化；可预测数据集仍可用静态流水。",
    },
    "2603.02176": {
        "constraint": "Skill 数量扩张后，flat registry 与一次检索无法同时解决发现、组合和质量退化。",
        "mechanism": "AgentSkillOS 先构建 capability tree 管理 Skill，再用 DAG 选择和编排多 Skill，把生态索引与任务执行分为两个状态阶段。",
        "evidence": "30 个 artifact-rich task、特定 Skill pool 和 LLM judge 支持规模效应观察；不证明安装量或树分类等价于真实质量。",
        "tradeoff": "可扩展发现换来 taxonomy 漂移、DAG planning cost 与 evaluator bias；小 Skill 集仍适合直接绑定。",
    },
    "2603.02188": {
        "constraint": "标准 multi-head attention 的 projection 与 KV 状态随 head/维度扩张，低秩共享可省参数但会损失 head diversity。",
        "mechanism": "Multi-Head Low-Rank Attention 在 head 结构内引入低秩参数化，重分配共享与每头特有表示。",
        "evidence": "作者结果支持其模型与 rank 下的质量/成本点；不证明统一 rank 适合所有层或长上下文。",
        "tradeoff": "压缩计算与状态换来表示瓶颈和 rank 选择；质量优先或小模型仍可保留 full-rank heads。",
    },
    "2603.02214": {
        "constraint": "多方协作推理既要共享能力又要保护输入、模型和收益归属，中心服务形成隐私与激励单点。",
        "mechanism": "Federated Inference 让参与方在受控协议下贡献局部模型/计算并聚合输出，同时将隐私与激励记账纳入 serving contract。",
        "evidence": "原型只支持作者 threat model、参与规模和任务；不证明串谋、掉线和经济机制在开放网络中稳定。",
        "tradeoff": "分散信任换来通信、同步、验证和支付复杂度；同一信任域内集中 serving 仍更高效。",
    },
    "2603.02240": {
        "constraint": "Multi-Agent 共享 memory 会跨任务传播 poisoned entry；仅按相似度检索无法表达来源可信度和隐私边界。",
        "mechanism": "SuperLocalMemory 保持本地记忆并用 Bayesian trust 更新来源可信度，使 memory admission/retrieval 同时受 provenance 与观测结果约束。",
        "evidence": "攻击/防御结果只覆盖作者 poisoning 模式、agent 与 prior；不证明 trust score 在分布变化或串谋下校准。",
        "tradeoff": "局部性与信任过滤降低污染传播，但牺牲共享召回并引入错误归因；可信单 Agent 场景可用简单 memory store。",
    },
    "2603.02271": {
        "constraint": "Edge VLA 的瓶颈不一定在视觉 encoder；动作生成的自回归频率、chunk 长度与控制周期会决定 latency。",
        "mechanism": "论文逐层 characterize perception、reasoning 与 action generation，把端侧优化 owner 从笼统模型压缩定位到动作生成路径。",
        "evidence": "瓶颈结论绑定测试 VLA、edge hardware 和控制设置；不能外推到 diffusion action head 或不同频率机器人。",
        "tradeoff": "针对动作路径优化更精确，但可能牺牲可迁移性；当视觉输入占主导时 encoder 优化仍是正确旧路径。",
    },
    "2603.02277": {
        "constraint": "Agent 能调用 shell/container 后，传统问答 safety benchmark 不能衡量连续探索、权限边界和真实 escape 能力。",
        "mechanism": "论文在隔离容器中提供可操作攻击面并记录多步行为，把 capability evaluation 绑定具体 sandbox、权限与成功条件。",
        "evidence": "结果只证明所测 frontier model 与漏洞集合；不证明未命中等于安全，也不覆盖生产容器全部配置。",
        "tradeoff": "真实执行提高外部效度但增加危险控制、复现和版本漂移；静态测试仍适合低风险早期筛查。",
    },
    "2603.02376": {
        "constraint": "分布式训练通常分别优化计算图和 collective，导致 operator placement 与网络拓扑互相制造等待。",
        "mechanism": "CUCo 让 agent 在统一搜索/反馈环中共同调整 compute schedule 与 communication plan，使两者共享 cost evidence。",
        "evidence": "收益绑定作者模型、集群拓扑和 search budget；不证明 agent 搜索比成熟专家规则在稳定集群上更可靠。",
        "tradeoff": "联合优化可减少局部最优，但增加搜索成本、测量噪声与不可解释 plan；固定拓扑仍可离线手工调优。",
    },
    "2603.02482": {
        "constraint": "多模态 safety evaluation 跨模型、输入资产和 run 配置时，按样例汇总会丢失运行 provenance。",
        "mechanism": "MUSE 以 run 为证据对象，版本化模型、数据、evaluator 和输出，使同一安全结论可重放和比较。",
        "evidence": "平台案例证明 run-centric schema 的组织能力；不证明其 benchmark 覆盖所有风险或 judge 无偏。",
        "tradeoff": "可追溯性换来 artifact 存储与 schema 治理；探索性实验可先轻量记录，发布 gate 才需要完整 run contract。",
    },
    "2603.02597": {
        "constraint": "在线或大规模数据管线中的 CPU BPE 会成为 accelerator 空闲的前置瓶颈，尤其是字节级预处理。",
        "mechanism": "GPUTOK 将 byte-level BPE 的匹配/合并搬到 GPU 并组织并行数据结构，改变 tokenizer 与 trainer/serving 的设备边界。",
        "evidence": "吞吐只属于作者词表、文本长度、GPU 和 baseline；未证明传输开销下所有 batch 都获益。",
        "tradeoff": "消除 CPU bottleneck 但占用 GPU、增加实现复杂度；小 batch 或 CPU 富余场景仍适合 CPU tokenizer。",
    },
    "2603.02599": {
        "constraint": "多模型 disaggregated serving 重复执行相近 next-token prediction，独立 prefill/decode 会浪费计算和 state movement。",
        "mechanism": "SUN 在多个 LLM 间共享 next-token prediction 结果/中间工作，令跨模型 serving runtime 管理可复用状态。",
        "evidence": "效率只对所测模型相似度、请求和硬件成立；不证明跨 family 共享不引入质量或隔离风险。",
        "tradeoff": "复用节省计算但要求 compatibility、provenance 与 tenant isolation；模型差异大时独立 serving 更稳健。",
    },
    "2603.02601": {
        "constraint": "Agent workflow 非确定，传统 golden-output regression 会把合法变化当失败，也可能漏掉步骤级退化。",
        "mechanism": "AgentAssay 选择高信息量 trace/断言并在 token budget 内重复测试，把 regression evidence 从单输出扩展到 workflow behavior。",
        "evidence": "作者任务上的检出率/成本支持其采样策略；不证明有限 run 能给出绝对可靠性或覆盖未建模 failure。",
        "tradeoff": "更经济的回归换来统计不确定与 evaluator 设计；确定性组件仍应使用普通 unit test。",
    },
    "2603.02631": {
        "constraint": "长上下文 prefill 成本高，但跨模型直接复用 KV 不兼容；小 draft 只能作为信息压缩器而非状态替代。",
        "mechanism": "Cross-Family Speculative Prefill 用小 draft 识别/压缩长上下文，再由目标模型验证，避免要求同 family KV 对齐。",
        "evidence": "延迟与质量绑定目标/草稿配对和长文任务；不证明压缩选择对所有推理问题无信息损失。",
        "tradeoff": "减少 prefill token 换来 draft pass 与漏证据风险；短输入或高精度检索任务仍应完整 prefill。",
    },
    "2603.02633": {
        "constraint": "analog-digital MoE 的器件噪声与专家异质性会放大 router/专家误差，平均精度不足以描述最坏行为。",
        "mechanism": "论文联合异构模拟/数字执行与鲁棒训练/理论界限，将硬件误差纳入专家和 routing 设计。",
        "evidence": "理论与实验只对其噪声模型、器件和 MoE 架构成立；不证明真实漂移完全匹配假设。",
        "tradeoff": "能效潜力换来校准、冗余和鲁棒训练成本；可靠性优先场景仍可全数字执行。",
    },
    "2603.02637": {
        "constraint": "GPU kernel agent 若只生成局部代码，无法保证编译、正确性、性能和框架集成的端到端闭环。",
        "mechanism": "StitchCUDA 用多 Agent 分解规格、实现、编译/测试和 rubric feedback，并通过 RL 优化整个程序交付轨迹。",
        "evidence": "成功率与性能只属于作者任务、rubric 和 toolchain；不证明生成 kernel 在未测 shape/数值边界上可靠。",
        "tradeoff": "自动化扩大搜索但增加执行成本和 reward hacking；安全关键 kernel 仍需人工 review 与 exhaustive test。",
    },
    "2603.02697": {
        "constraint": "多 Agent 若各自生成场景视频，独立 latent/world state 会导致同一共享世界出现不一致。",
        "mechanism": "ShareVerse 维护共享场景约束并协调多 Agent 生成，使视角/角色输出引用同一 world state。",
        "evidence": "一致性结果只覆盖作者场景、生成模型和 metric；不证明视觉一致等价于物理或因果正确。",
        "tradeoff": "共享状态提高一致性但限制各 Agent 自由度并增加同步；独立创作任务无需强一致 world model。",
    },
    "2603.02731": {
        "constraint": "FP4 训练可降带宽和显存，但 MoE 的激活、router 与稀疏专家对低精度误差敏感；Hopper 也缺少全部原生路径。",
        "mechanism": "论文通过 scale、cast、accumulation 和敏感算子保留策略在 Hopper 上组织可实践 FP4 MoE training。",
        "evidence": "收敛和效率绑定作者模型、Hopper kernel 与训练长度；不证明更大规模或不同数据仍等价。",
        "tradeoff": "资源收益换来 scaling/overflow 调试与混合精度例外；训练稳定性优先时 BF16/FP8 仍合理。",
    },
    "2603.02737": {
        "constraint": "wafer-scale SRAM 容量和片上通信改变 LLM inference 的瓶颈，GPU 式 layer-at-a-time schedule 不能直接复用。",
        "mechanism": "Ouroboros 采用 token-grained pipeline 在 wafer 上流动 token/层状态，使 SRAM 计算阵列按数据流协同。",
        "evidence": "性能来自作者架构模型/模拟和映射；不证明制造、yield、软件栈和生产成本。",
        "tradeoff": "片上带宽换来专用硬件和 pipeline bubble/映射约束；通用模型变化频繁时 GPU 更灵活。",
    },
    "2603.02885": {
        "constraint": "多租户 LoRA/fine-tuning 为每任务复制 backbone 或串行运行会浪费显存和时间，但共享又可能互相干扰。",
        "mechanism": "MuxTune 在空间和时间上复用 backbone 计算/参数，只隔离 tenant-specific 更新与状态。",
        "evidence": "吞吐/隔离结果只覆盖作者模型、任务组合和 datacenter；不证明任意 optimizer/state 都可安全复用。",
        "tradeoff": "复用提高利用率但增加调度、干扰和故障域；强隔离或单大任务仍适合独占训练。",
    },
    "2603.03116": {
        "constraint": "Agent 即使最终任务成功，也可能伪造步骤、越权或违反程序；只看 utility 会把 corrupt success 当通过。",
        "mechanism": "Procedure-Aware Evaluation 将规范过程编码为四个评估轴，并对 execution trace 与结果联合审计。",
        "evidence": "作者在 -bench、三类模型和人工核验上展示 corrupt success；不证明 LLM judge 对所有程序约束可靠。",
        "tradeoff": "过程审计提高安全语义但需要规范、trace 和 judge 成本；结果唯一且无副作用的任务可继续 outcome-only。",
    },
    "2603.03205": {
        "constraint": "Tool-using reasoning model 需要在有害请求中拒绝、在良性任务中行动；静态拒绝会过度阻断，纯 CoT 又缺少显式安全目标。",
        "mechanism": "MOSAIC 通过结构化 safety reasoning、rollout 和 composite reward 训练 act/refuse 决策。",
        "evidence": "结果覆盖 Agent-SafetyBench、AgentHarm、BFCL 与所测模型；不证明对新工具或提示注入保持校准。",
        "tradeoff": "显式安全 scaffold 降低有害行动但增加 token、judge bias 和 over-refusal；低风险工具可使用更轻 policy gate。",
    },
    "2603.03251": {
        "constraint": "speculative decoding 的 draft 自身也可被推测；单层 speculation 留下可利用的层级并行空间。",
        "mechanism": "Speculative Speculative Decoding 构造嵌套草稿/验证层，使较小预测器为中间 draft 加速，再由目标模型保持最终校验。",
        "evidence": "加速只属于作者模型层级、接受率和硬件；不证明额外层总能抵消 orchestration cost。",
        "tradeoff": "更多并行机会换来复杂 pipeline 和错误相关；短序列或低接受率时单层 speculation 更好。",
    },
    "2603.03290": {
        "constraint": "lifelong Agent memory 需要跨会话写入、更新、遗忘与检索；只追加 embedding store 会积累冲突和噪声。",
        "mechanism": "AriadneMem 把记忆组织为可追踪 thread，并按事件关系维护生命周期，使 retrieval 引用演进状态而非孤立片段。",
        "evidence": "作者 benchmark 支持长时程任务中的改进；不证明 thread construction 对开放域事实始终正确。",
        "tradeoff": "结构化生命周期提高一致性但增加更新、合并和错误传播；短会话可继续用简单 context/RAG。",
    },
    "2603.03333": {
        "constraint": "semantic token speculative decoding 的 acceptance 若只用确定性阈值，会在不确定边界拒绝可接受 draft 或接受偏差。",
        "mechanism": "论文对 acceptance 进行 training-free dropout sampling，用预测不确定性调节语义接受。",
        "evidence": "结果绑定作者 semantic tokenizer、dropout 和任务；不证明采样保持 exact autoregressive distribution。",
        "tradeoff": "更灵活接受换来随机性、校准和复现成本；要求严格 exactness 时仍用标准 rejection sampling。",
    },
    "2603.03378": {
        "constraint": "Cloud diagnosis Agent 的失败轨迹通常被丢弃，但其中包含工具选择和假设修正信号。",
        "mechanism": "AOI 将失败 trajectory 解析成可训练/可反思的中间反馈，让 autonomous diagnosis 从错误过程更新策略。",
        "evidence": "改进只覆盖作者 cloud tasks、错误标签和 agent；不证明自动归因的失败原因真实。",
        "tradeoff": "复用失败数据提高样本效率，但可能强化错误 hindsight；因果不清时仍需人工 incident review。",
    },
    "2603.03379": {
        "constraint": "LLM 自己评估每个 memory candidate 的检索价值成本高，纯 embedding 又忽略 outcome utility。",
        "mechanism": "MemSifter 用 outcome-driven proxy 学习 memory selection，把重型 reasoning 从在线检索路径卸载。",
        "evidence": "结果只对作者 memory tasks、proxy label 和 base model；不证明 proxy 在策略变化后仍校准。",
        "tradeoff": "降低在线成本但引入代理漂移和反馈回路；低流量或高风险场景仍可直接让主模型评估。",
    },
    "2603.03380": {
        "constraint": "端侧 VLA 同时受模型容量、内存、能耗与控制周期约束，服务器级多模态控制无法直接部署。",
        "mechanism": "LiteVLA-Edge 对多模态表示和 action path 做量化/轻量化，使推理驻留设备并闭合本地控制回路。",
        "evidence": "成功率和 latency 只属于所测 robot、quantization 与 embedded hardware；不证明复杂环境安全。",
        "tradeoff": "本地低延迟与隐私换来容量/精度下降；高难任务或网络稳定时云端模型仍可作高层规划器。",
    },
    "2603.03394": {
        "constraint": "AI sandbox 若只隔离进程，不处理 policy、审批、数据分级和审计，就无法满足治理要求。",
        "mechanism": "论文把 governance policy、runtime isolation、action mediation 和 evidence logging 组合成 sandbox contract。",
        "evidence": "工程经验展示设计与 lessons learned，但缺少统一实验节可复算所有安全属性。",
        "tradeoff": "治理可审计性增加配置、审批延迟和运维；低风险离线实验可用较轻隔离。failure 是 policy/runtime 配置漂移。",
    },
    "2603.03403": {
        "constraint": "跨不互信组件的 workflow 不能因为单个组件声明成功就建立端到端信任。",
        "mechanism": "论文用 attestation 将每一步代码/环境/输入输出承诺串成 workflow evidence chain，使信任来自可验证组合。",
        "evidence": "实验/原型只证明所用 attestation stack 和 threat model；不证明被证明代码本身无逻辑错误。",
        "tradeoff": "可组合信任换来证明、密钥和版本管理；同一可信域可用普通 provenance。failure 包括 evidence gap 与 replay。",
    },
    "2603.03482": {
        "constraint": "以 pixel history 表示 world state 会随时间增长且难维持物体 identity、遮挡和几何一致。",
        "mechanism": "论文维护 persistent 3D state，并用新 observation 更新该状态再生成/预测，令世界身份独立于最近帧。",
        "evidence": "结果支持作者场景中的持久性与生成质量；不证明 3D state 是真实因果状态或覆盖动态物理。",
        "tradeoff": "一致状态换来重建、更新和误差累积；短视频生成仍可只用 frame history。",
    },
    "2603.03491": {
        "constraint": "Compute-in-Memory accelerator 的微小器件变化可能经网络层放大，平均-case 精度掩盖 worst-case reliability。",
        "mechanism": "论文结合 selective write-verify 与 right-censored noise learning，在硬件写入和训练层分别控制变异传播。",
        "evidence": "分析证明特定 variation model 下的失败与缓解；未披露完整通用 benchmark，不能外推所有 CIM 工艺。",
        "tradeoff": "可靠性换来 verify 写开销和训练假设；稳定器件或容错 workload 可省略 selective verification。",
    },
    "2603.03589": {
        "constraint": "massive agent-centric ML workload 包含大量短任务、动态 DAG、环境和 artifact，传统固定 training job abstraction 过重。",
        "mechanism": "stratum 提供面向 Agent run 的共享执行、状态和调度基础设施，把细粒度任务生命周期从单 agent 进程上移。",
        "evidence": "作者 workload 上的规模和效率支持该 runtime；不证明所有 agent 框架都能无损映射。",
        "tradeoff": "共享基础设施提高复用但增加平台耦合、隔离和 backpressure；少量长任务仍可直接用 batch job。",
    },
    "2603.03731": {
        "constraint": "supernode 内高速互联与跨 supernode 网络差异巨大，拓扑无感并行会把 collective 放到昂贵链路。",
        "mechanism": "HyperParallel 让 parallel plan 感知 supernode affinity，联合映射 TP/PP/DP 与设备层级。",
        "evidence": "框架结果绑定作者 supernode、模型和网络；缺失 facet 保持 Not Disclosed，不能宣称跨集群普适。",
        "tradeoff": "拓扑亲和减少通信但限制 placement 灵活性和故障恢复；均匀网络上通用调度更简单。",
    },
    "2603.03772": {
        "constraint": "AI×DB workload 在 query、embedding、训练和 inference 间共享 CPU/GPU/IO，独立 scheduler 会制造跨系统争用。",
        "mechanism": "论文用统一 orchestration 表达 AI 与 DB stage 的资源和依赖，使调度拥有端到端 workflow 而非单引擎任务。",
        "evidence": "案例/实验支持所测混合 workload；不证明一个 scheduler 能替代所有数据库内部优化。",
        "tradeoff": "跨域优化换来接口标准化和更大故障域；单一 DB 或离线 AI 任务仍可独立运行。",
    },
    "2603.03784": {
        "constraint": "生成式 world model 缺少可执行规格时，视觉 plausible 无法证明 event order、guard 和状态转移正确。",
        "mechanism": "论文用 DEVS formalism 生成并评估 discrete-event world model，将状态、事件和 transition contract 显式化。",
        "evidence": "结果只证明作者规格/场景中的结构符合度；exact-v1 未提供独立 limitations 节，不证明连续物理世界可同样表达。",
        "tradeoff": "规格驱动提高可验证性但要求领域建模并限制开放生成；探索性视频 world model 可保留弱结构。",
    },
    "2603.03800": {
        "constraint": "真实任务只有稀疏 outcome，直接训练 reward/critic 难区分过程质量并易过拟合成功标签。",
        "mechanism": "论文用 rubric 将稀疏 outcome 转成结构化 critic supervision，指导中间判断。",
        "evidence": "作者任务中的 critic/reward 结果支持该监督；不证明 rubric 无偏或能覆盖未知 failure。",
        "tradeoff": "增加过程信号但引入 rubric 设计和 judge 成本；可形式验证任务仍优先 programmatic verifier。",
    },
    "2603.04028": {
        "constraint": "去中心化 LLM inference 参与者异质且可能作弊，单一 latency/quality 指标不能支持可信选择和结算。",
        "mechanism": "论文构造多维 quality score 与 proof-of-quality，把模型输出、服务属性和验证 evidence 绑定。",
        "evidence": "结果只覆盖作者网络、评分权重和验证流程；不证明分数不可操纵或等价于用户效用。",
        "tradeoff": "可验证市场换来额外评测、共识和延迟；可信集群内不需要完整 proof layer。",
    },
    "2603.04241": {
        "constraint": "Agentic data workflow 只靠自然语言步骤缺少类型、可组合性和 map-reduce 执行语义，难以验证与优化。",
        "mechanism": "Agentics 2.0 定义 logical transduction algebra、grounded types 与 transducible operator，将自然语言数据变换编译为 typed workflow。",
        "evidence": "DiscoveryBench 和 NL-to-SQL 结果支持作者实现；不证明 algebra 覆盖任意副作用工具或事务语义。",
        "tradeoff": "类型化提高组合与审计，但限制自由表达并需要 schema；小型一次性 workflow 可直接脚本化。",
    },
    "2603.04257": {
        "constraint": "长时程 Agent 仅靠当前 context 无法保留大量经历，原始 replay 又造成检索和 token 成本。",
        "mechanism": "Memex(RL) 将经验写入可索引 memory，并用 RL 学习何时检索/复用，使经验成为 policy 可调用状态。",
        "evidence": "结果只覆盖作者长任务、index 和训练方案；不证明 retrieved experience 因果正确或不会污染。",
        "tradeoff": "扩展 horizon 换来索引漂移、检索成本和旧经验偏差；短任务仍可完全依赖 context。",
    },
    "2603.04308": {
        "constraint": "Transformer activation outlier 破坏低比特量化，但不同层/通道的 outlier 统计和部署影响常被单一平均值掩盖。",
        "mechanism": "论文复现并统计 outlier 分布，再连接 quantization choice 与 deployment cost，强调按层/算子处理。",
        "evidence": "结果只对所测模型、数据、bit format 和硬件；不证明某一种旋转/裁剪 universally best。",
        "tradeoff": "定向处理保精度但增加 calibration、kernel 特化和维护；精度/带宽宽裕时高精度路径更稳。",
    },
    "2603.04379": {
        "constraint": "实时长视频生成同时受历史漂移、token/step 数和系统吞吐约束，单纯提高生成质量无法闭合实时性。",
        "mechanism": "Helios 组合 history injection、anti-drifting、深压缩 predictor-corrector 与 memory/efficiency infrastructure，联合减少状态和采样步骤。",
        "evidence": "定量、用户研究和 ablation 只支持作者模型、视频长度和硬件；不证明实时结论跨分辨率或并发成立。",
        "tradeoff": "实时与长一致性换来压缩误差、蒸馏和复杂系统；离线高质量生成仍可使用更多 steps。",
    },
    "2603.04402": {
        "constraint": "搜索 Agent benchmark 分散在不同平台、接口和 retriever，结果不可归因于策略还是环境。",
        "mechanism": "SearchGym 提供模块化平台 adapter、统一 trace 和 hybrid search orchestration，使跨平台实验共享 contract。",
        "evidence": "benchmark 只证明纳入平台和任务中的比较；不证明平台 API 漂移后仍可复现。",
        "tradeoff": "可比性换来 adapter 维护和最小公分母抽象；单平台优化可直接使用原生接口。",
    },
    "2603.04411": {
        "constraint": "统一 KV 压缩率忽略 token 重要性变化，会在不重要 token 上浪费状态或删除关键 token。",
        "mechanism": "论文按 token 动态选择压缩强度，使 KV precision/retention 成为 token-wise decision。",
        "evidence": "质量与内存只绑定作者模型、任务和压缩器；不证明重要性估计在分布外稳定。",
        "tradeoff": "细粒度节省更多状态但增加 metadata 和 kernel irregularity；均匀短上下文可用固定压缩。",
    },
    "2603.04417": {
        "constraint": "LLM judge 对相同输入在模型和重复运行间给出不同分数，单次平均掩盖 evaluator identity 与方差。",
        "mechanism": "论文跨多 judge/model 重复测量一致性，将 variance 与 disagreement 纳入 evaluation contract。",
        "evidence": "研究证明所测 judge/任务存在不一致；不证明任何替代 judge 天然可靠，也不提供绝对真值。",
        "tradeoff": "重复/多 judge 提高不确定性可见性但增加成本；低风险筛选可容忍单 judge，release gate 不应。",
    },
    "2603.04424": {
        "constraint": "分布式训练扩容若只看 GPU 数，会忽略 fabric topology、oversubscription 和 collective contention，出现 scaling 反转。",
        "mechanism": "论文把网络/fabric 事件与训练 step/collective trace 对齐，定位何时 topology 成为训练 owner 约束。",
        "evidence": "结果只覆盖所测集群、模型和 collective；不证明同一阈值适用于其他 fabric。",
        "tradeoff": "网络感知 placement/并行提高效率但降低可调度池和容错弹性；小规模或均匀网络仍可简单扩容。",
    },
    "2603.04427": {
        "constraint": "KV key 和 value 对 attention 选择与内容恢复承担不同责任，等宽压缩可能在 value 上损失过多。",
        "mechanism": "Thin Keys, Full Values 只把 key 投影到低维用于选择，保留完整 value 承载内容。",
        "evidence": "内存/质量结果绑定作者 attention、projection 和任务；不证明低维 key 对所有 head/层保序。",
        "tradeoff": "保 value 提高质量但节省上限低于双侧压缩，且增加 mixed-layout kernel；内存极紧时仍需压 value。",
    },
    "2603.04428": {
        "constraint": "Edge multi-agent 反复重建 prompt/KV 会浪费延迟和能耗，普通 memory store 不能直接复用解码状态。",
        "mechanism": "论文将持久 Q4 KV 作为 prompt 下方的 agent memory，并管理跨 agent/session 的缓存 identity。",
        "evidence": "收益只对作者模型、edge device、Q4 与复用模式；不证明缓存跨权重/位置变化仍有效。",
        "tradeoff": "低延迟换来 stale state、量化误差和隔离风险；低复用或模型频繁升级时应重建 KV。",
    },
    "2603.04443": {
        "constraint": "长运行 Agent memory 会无限增长并造成 tail latency；只按容量 eviction 不能表达创建、热度、压缩和淘汰阶段。",
        "mechanism": "AMV-L 用 lifecycle manager 管理 memory 的写入、分层、压缩和回收，以尾延迟 SLO 驱动状态迁移。",
        "evidence": "结果只覆盖作者 workload、层级和硬件；不证明所有 memory value 都可由访问热度代表。",
        "tradeoff": "控制 tail latency 但增加预测、迁移和一致性；小 memory 或无 SLO 场景可直接保留。",
    },
    "2603.04444": {
        "constraint": "Mixture-of-Modality 请求对模型、encoder 和资源需求不同，静态 endpoint routing 无法从输入信号匹配执行路径。",
        "mechanism": "vLLM Semantic Router 从请求语义/模态信号选择后端与策略，把 routing decision 置于 serving admission。",
        "evidence": "结果只对配置的模型池、信号和 traffic；不证明 router 在分布漂移下保持质量或公平。",
        "tradeoff": "提高匹配效率但增加分类延迟、错误路由和 fallback；单模型服务无需语义 router。",
    },
    "2603.04448": {
        "constraint": "Skill registry 只存文件无法回答能力重复、质量、关系和可组合性，生态扩大后检索会退化。",
        "mechanism": "SkillNet 从经验抽象 Skill，建立 ontology，过滤合并并评估连接，使 Skill 成为有版本和关系的资产。",
        "evidence": "定量与应用场景只覆盖作者数据和 evaluator；不证明自动抽象出的 Skill 在任意 Agent 中可移植。",
        "tradeoff": "生态治理换来 ontology/evaluation 成本和错误合并风险；小型人工 curated Skill 集仍更可控。",
    },
    "2603.04459": {
        "constraint": "安全 benchmark 的引用影响力与代码仓库质量不等于测量有效性，但实践中常被当作可信代理。",
        "mechanism": "论文同时审计 benchmark influence 与 repository 可运行/维护属性，分离社会采用和 artifact quality。",
        "evidence": "结果证明所采样 benchmark 的差异；不证明高仓库质量意味着安全 construct validity。",
        "tradeoff": "多维审计提高选择依据但增加维护与主观规则；早期探索可使用较轻清单，release gate 需更严格。",
    },
    "2603.04460": {
        "constraint": "长上下文 prefill 的全注意力成本高，通用稀疏模式又可能错过垂直/斜向长程依赖。",
        "mechanism": "VSPrefill 用 vertical-slash sparse pattern 与轻量索引选择 key block，专门优化 prefill 数据流。",
        "evidence": "速度/质量只属于作者模型、长度、GPU 和 pattern；不证明所有任务注意力都呈该结构。",
        "tradeoff": "减少计算但引入索引和漏依赖风险；短上下文或依赖稠密任务仍用 full attention。",
    },
    "2603.04621": {
        "constraint": "GPU execution 若只优化单算子，会在双路径/流水衔接、内存与同步上留下系统瓶颈。",
        "mechanism": "DuaLip-GPU 设计双 pipeline 协同计算和数据搬运，以端到端 plan 管理 overlap。",
        "evidence": "技术报告结果绑定作者 kernel、shape 与 GPU；不证明框架集成、并发和数值边界。",
        "tradeoff": "更强 overlap 换来调度和资源竞争复杂度；算子小或无可重叠 I/O 时普通执行更简单。",
    },
    "2603.04797": {
        "constraint": "LLM serving 的 KV/weight 带宽与容量使传统 HBM hierarchy 受限，3D-DRAM 需要软件共同决定映射。",
        "mechanism": "论文联合 3D-DRAM accelerator 与 serving dataflow/placement，按模型状态访问模式设计硬件。",
        "evidence": "性能来自作者模型/模拟或原型；不证明封装、热、成本和软件生态。",
        "tradeoff": "更高带宽/容量换来专用硬件与映射锁定；快速变化模型仍适合通用 GPU。",
    },
    "2603.04833": {
        "constraint": "Multi-Agent RL 全连接通信随 Agent 数增长，固定分组又忽略信息效用和时间变化。",
        "mechanism": "SCoUT 根据消息/协作 utility 动态进行 temporal grouping，只在有收益时建立通信。",
        "evidence": "结果只覆盖作者 MARL 环境、utility estimator 和规模；不证明 LLM-MAS 或开放环境同样成立。",
        "tradeoff": "降低通信换来估计错误与拓扑抖动；小团队或强全局耦合任务仍可全连接。",
    },
    "2603.04902": {
        "constraint": "Agent workflow 的隐私风险取决于上下文目的、角色和信息流；仅检测 PII 无法判断传递是否合规。",
        "mechanism": "AgentSCOPE 用 Privacy Flow Graph 表示 actor、context 与 transmission，并据 contextual integrity 构造 benchmark。",
        "evidence": "实验揭示所测 agent/workflow 的 privacy failure；不证明 graph policy 覆盖所有法律或组织规范。",
        "tradeoff": "语义化隐私检查提高精度但需要政策建模和 provenance；简单数据脱敏仍适合明确字段。",
    },
    "2603.04910": {
        "constraint": "VLA 的 Markov observation 难以处理遮挡、迟延和长期目标，单一短期 memory 不足。",
        "mechanism": "VPWEM 将 working 与 episodic memory 接入 visuomotor policy，使动作依赖近期状态和历史事件。",
        "evidence": "结果只覆盖作者 robot/task 和 memory design；不证明 episodic retrieval 在分布外可靠。",
        "tradeoff": "处理非 Markov 状态但增加 stale memory 和检索延迟；完全可观测短任务仍用无记忆 policy。",
    },
    "2603.04981": {
        "constraint": "动态数据选择中，代表性与多样性会随模型和数据分布变化；一次性静态 subset 很快失效。",
        "mechanism": "论文重新定义/联合优化 representativeness 与 diversity，并按训练反馈更新选择。",
        "evidence": "结果只对作者数据、模型和选择预算；不证明指标等价于长期泛化或公平。",
        "tradeoff": "动态适配提高样本效用但增加选择开销和反馈偏差；稳定分布可使用静态 curated data。",
    },
    "2603.05147": {
        "constraint": "VLA 每一步都长推理会错过控制周期，永远快速行动又会在复杂状态犯错。",
        "mechanism": "论文按状态复杂度在 act、think、abstain 三条路径间选择，将推理预算和安全拒绝纳入 controller。",
        "evidence": "收益只覆盖作者复杂度估计、机器人和任务；不证明门控在未知风险中校准。",
        "tradeoff": "自适应计算降低平均 latency，但错误门控会延迟或危险行动；固定安全关键回路仍需确定性控制。",
    },
    "2603.05185": {
        "constraint": "长时程 manipulation 中，高层 VLA 计划会积累错误，低层 controller 又无法判断语义目标是否偏离。",
        "mechanism": "tri-system VLA 加入独立 critic，在 perception/reasoning-action 与执行反馈间审查并触发修正。",
        "evidence": "实验只证明作者 manipulation 任务中的恢复；不证明 critic 独立于 actor 错误或满足实时 SLO。",
        "tradeoff": "反馈纠错提高鲁棒性但增加 latency 和 correlated judge failure；短、确定动作仍可两层控制。",
    },
    "2603.05210": {
        "constraint": "speculative decoding 缩小 draft vocabulary 可降低草稿延迟，却会降低 target token 覆盖和接受率。",
        "mechanism": "论文联合选择 vocabulary coverage 与 draft cost，在模型/工作负载上寻找平衡点。",
        "evidence": "速度只属于作者词表、模型配对和硬件；不证明静态 trimmed vocabulary 对领域漂移稳健。",
        "tradeoff": "更快 draft 换来覆盖缺口与 fallback；开放域或低可预测文本应保留更大词表。",
    },
    "2603.05399": {
        "constraint": "LLM judge 平均相关性无法揭示顺序、风格、重复和对抗输入下的可靠性退化。",
        "mechanism": "Judge Reliability Harness 对 judge 进行成组 stress test 并保存 evaluator/version/seed 证据。",
        "evidence": "结果揭示所测 judge 的 failure；不证明 harness 场景穷尽真实偏差或能给出真值。",
        "tradeoff": "系统性压力测试增加样本与人审成本；探索性排序可用单 judge，发布结论需多证据。",
    },
    "2603.05438": {
        "constraint": "latent world model 的规划 token 过长会增加 rollout 成本，过度压缩又会丢失可控状态。",
        "mechanism": "论文学习紧凑离散 tokenizer，用少量 token 表达 planning-relevant latent state。",
        "evidence": "8-token 结果只属于作者环境、tokenizer 和 planner；不证明 token 保留所有安全相关因素。",
        "tradeoff": "规划更快但产生信息瓶颈与不可解释 code；复杂/开放世界仍需更丰富状态。",
    },
    "2603.05451": {
        "constraint": "新硬件计算/带宽缩放不对称，旧 FlashAttention pipeline 的 stage 平衡会失效。",
        "mechanism": "FlashAttention-4 联合重排算法 tiles 与 kernel pipeline，使 load、compute 和 reduce 匹配非对称硬件。",
        "evidence": "性能绑定作者 GPU、dtype、shape、并发和 kernel；不证明未来硬件或所有 attention 变体。",
        "tradeoff": "硬件特化带来速度但增加复杂度、shape cliff 和维护；不支持平台继续使用通用 SDPA。",
    },
    "2603.05454": {
        "constraint": "Diffusion LM 的 block/token 接受若零散，会破坏连贯进展并增加迭代与状态提交成本。",
        "mechanism": "论文选择 longest stable prefix 作为连续 commit 单元，使 DLM 在多轮修正中保留一致前缀。",
        "evidence": "速度/质量只对作者 DLM、稳定判据和任务；不证明 prefix stability 等价于全局正确。",
        "tradeoff": "连贯提交减少回滚但可能保守等待或固化早期错误；高并行且可自由修正任务可继续 scattered acceptance。",
    },
}
