#!/usr/bin/env python3
"""Build the 2025-05-01 V2.1 Daily from the frozen exact-window source packet."""

from __future__ import annotations

import hashlib
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[6]
REPORT = ROOT / "papers/2025/05/01/README.md"


def c(fid, aid, title, published, score, node, disposition, chapter, adjacent,
      existing, delta, relation, method, evaluation, limits, artifact, claim,
      review, benchmark="yes", override="none"):
    dd, sr, dur = score
    total = sum(score)
    return {
        "fid": fid, "aid": aid, "title": title, "published": published,
        "score": score, "total": total, "node": node,
        "disposition": disposition, "chapter": chapter, "adjacent": adjacent,
        "existing": existing, "delta": delta, "relation": relation,
        "method": method, "evaluation": evaluation, "limits": limits,
        "artifact": artifact, "claim": claim, "review": review,
        "benchmark": benchmark, "override": override,
        "route": "deep" if total >= 7 or override != "none" or disposition == "Integrate" else "standard",
    }


C = [
    c("SF-2025-COSMOS-ADAPTATION", "2505.01449", "COSMOS: Predictable and Cost-Effective Adaptation of LLMs", "2025-04-30T02:06:26Z", (2,2,2), "PLATFORM-COST", "Integrate", "books/part-06-ai-infrastructure/70-cost.md#L1", "books/part-06-ai-infrastructure/66-evaluation-system.md#L1; books/part-04-training-system/29-sft.md#L1", "成本章已有训练、推理和资源账本，但没有把 fine-tuning 与 retrieval-augmented ICL 写成受预算约束的 adaptation portfolio。", "把 quality/cost predictor 只作为 strategy proposal，最终选择仍由冻结 workload、数据访问、hardware price 与 evaluation gate 决定。", "Alternative Branch", "https://arxiv.org/html/2505.01449v1#S3; https://arxiv.org/html/2505.01449v1#S4", "https://arxiv.org/html/2505.01449v1#S5; https://arxiv.org/html/2505.01449v1#A4", "https://arxiv.org/html/2505.01449v1#S6; https://arxiv.org/html/2505.01449v1#A9", "Not Disclosed — exact-v1 does not publish a frozen implementation artifact used in this review", "adaptation 不是先固定方法再计算账单；在 data/task/model/hardware contract 冻结后，可以先预测 fine-tuning、retrieval-ICL 及组合路径的 quality/cost，再由平台作有证据边界的选择。", "作者把策略选择形式化为性能与成本联合预测，比较 fine-tuning、retrieval-augmented ICL 及组合路径。该证据只支持论文的数据集、模型族、pricing/hardware 假设；预测器不拥有真实 deployment outcome，分布漂移、价格变化和训练失败都要求重新校准。", override="knowledge_gap"),
    c("SF-2025-ZIPLLM-STORAGE", "2505.06252", "ZipLLM: Efficient LLM Storage via Model-Aware Synergistic Data Deduplication and Compression", "2025-04-30T04:16:32Z", (3,3,3), "PLATFORM-MODEL-REGISTRY", "Integrate", "books/part-06-ai-infrastructure/59-model-registry.md#L105", "books/part-06-ai-infrastructure/58-kubeflow.md#L1; books/part-06-ai-infrastructure/60-training-operator.md#L1", "Registry 已区分 metadata/index 与 artifact store，但尚未说明大量同源 checkpoint 的物理存储可以怎样共享而不破坏 artifact identity。", "在 artifact-store 一侧增加 tensor-level dedup、family clustering 与 lossless delta compression；Registry 仍保存逻辑模型、base/delta lineage、完整性 hash 与可独立 materialize 的部署引用。", "Layering / Dependency", "https://arxiv.org/html/2505.06252v1#S3; https://arxiv.org/html/2505.06252v1#S4", "https://arxiv.org/html/2505.06252v1#S5; https://arxiv.org/html/2505.06252v1#A1", "https://arxiv.org/html/2505.06252v1#S6; https://arxiv.org/html/2505.06252v1#S7", "https://storageai.github.io/ZLLM/ — project artifact linked from exact-v1", "物理去重不能合并逻辑模型身份：同源 checkpoint 可共享相同 tensor/chunk，并以 lossless delta materialize，但 base/delta lineage、hash、authorization 与独立恢复路径必须保持。", "论文从 Hugging Face model families 的 storage redundancy 出发，组合 tensor-level dedup、聚类和 BitX delta compression，并测量空间与恢复/serving throughput。它不证明任意 quantized/encrypted artifact 都可共享，也不允许 Registry 把物理共用误写成同一模型；聚类误判、base deletion 与恢复放大成为新 failure mode。", override="knowledge_gap"),
    c("SF-2025-BAYES-EVAL-CONFIDENCE", "2504.21303", "Confidence in Large Language Model Evaluation: A Bayesian Approach to Limited-Sample Challenges", "2025-04-30T04:24:50Z", (3,3,3), "PLATFORM-EVALUATION-SYSTEM", "No Change — Existing Coverage", "books/part-06-ai-infrastructure/66-evaluation-system.md#L1040", "books/part-06-ai-infrastructure/65-kai-scheduler.md#L1; books/part-06-ai-infrastructure/67-monitoring.md#L1", "Evaluation 章已把 point estimate、confidence/calibration、相关误差与 abstention 分开，并要求冻结 evaluator identity。", "有限样本 Bayesian ranking 是该既有命题的一种实现：posterior 只属于给定 prior、anchor、query set 与 judge，不是模型的内在置信度。", "Principle Reuse", "https://arxiv.org/html/2504.21303v1#S2; https://arxiv.org/html/2504.21303v1#S2.SS2", "https://arxiv.org/html/2504.21303v1#S3; https://arxiv.org/html/2504.21303v1#S4", "https://arxiv.org/html/2504.21303v1#S5.SS1", "Not Disclosed — exact-v1 does not identify a released evaluation implementation", "有限 query 上的模型排序必须输出 posterior uncertainty，并把 prior、anchor model、query construction 和 judge 一起纳入 evaluation identity；高 posterior 不是跨分布正确性证明。", "论文用 Bayesian inference 估计有限样本下相对成功率并与传统排名比较。结果支持在相同 query/judge contract 下表达排序不确定性；它不证明 prior 无偏、judge 正确或 posterior 能转移到新任务，anchor 与 query selection 会成为新的偏差来源。"),
    c("SF-2025-PHI4-REASONING", "2504.21318", "Phi-4-reasoning Technical Report", "2025-04-30T05:05:09Z", (2,2,2), "TRAIN-SFT", "No Change — Existing Coverage", "books/part-04-training-system/29-sft.md#L1", "books/part-04-training-system/28-pretraining.md#L1; books/part-04-training-system/33-grpo.md#L1", "SFT/GRPO 章节已经把 teacher demonstrations、cold start、outcome-verifiable RL 与长输出代价写成条件分支。", "Phi-4-reasoning 是 compact model 上 teachable-prompt SFT 加短程 RL 的受限实例，不新增独立 owner。", "Direct Evolution", "https://arxiv.org/html/2504.21318v1#S2; https://arxiv.org/html/2504.21318v1#S3; https://arxiv.org/html/2504.21318v1#S4", "https://arxiv.org/html/2504.21318v1#S5; https://arxiv.org/html/2504.21318v1#A1", "https://arxiv.org/html/2504.21318v1#S6", "https://github.com/microsoft/eureka-ml-insights — linked evaluation artifact; full training stack Not Disclosed", "compact reasoning policy 可由高可教性 demonstration 扩展，再用 outcome-verifiable RL 增加探索；teacher/scaffold 和 token budget 仍是能力与成本边界。", "技术报告披露 seeds/data、SFT exploration/scaling 和 reasoning-plus RL，并在 reasoning/general/safety benchmark 上评估。它不披露完整训练 hardware、batch/concurrency 或生产 SLO，也不证明长 trace 忠实；旧的短响应模型在严格 latency 下仍合理。"),
    c("SF-2025-NEXUS-GEN", "2504.21356", "Nexus-Gen: Unified Image Understanding, Generation, and Editing via Prefilled Autoregression in Shared Embedding Space", "2025-04-30T06:30:48Z", (2,2,2), "MULTIMODAL-REPRESENTATION", "No Change — Existing Coverage", "books/part-03-multimodal-world-models/23-multimodal-representation.md#L160", "books/part-03-multimodal-world-models/24-multimodal-generative-paradigms.md#L1; books/part-02-model/18-decoder-only.md#L1", "多模态章节已区分 shared semantic interface 与独立 generation head，并把 AR factorization 放在生成范式 owner。", "shared embedding、task token 与 prefilled autoregression 是该分层的实现案例；case study 不足以宣称统一表示优于所有双塔。", "Layering / Dependency", "https://arxiv.org/html/2504.21356v1#S2.SS1; https://arxiv.org/html/2504.21356v1#S2.SS2; https://arxiv.org/html/2504.21356v1#S2.SS3", "https://arxiv.org/html/2504.21356v1#S3", "Not Disclosed — exact-v1 has no dedicated limitations section and provides qualitative case studies rather than a matched broad benchmark", "https://github.com/modelscope/Nexus-Gen.git — repository linked from exact-v1", "统一多模态模型仍需分开 representation identity 与 generation state：shared space 负责接口，prefilled AR 负责条件生成与 commit 顺序。", "论文给出 architecture、unified task representation、prefilled autoregression 与数据构建，并展示理解/生成/编辑案例。缺少系统性 matched benchmark、ablation 和 production latency，因此只支持可行性，不证明共享空间消除了 modality boundary 或独立 head 的必要性。", benchmark="no"),
    c("SF-2025-SHORTERBETTER", "2504.21370", "ShorterBetter: Guiding Reasoning Models to Find Optimal Inference Length for Efficient Reasoning", "2025-04-30T07:04:19Z", (2,2,2), "INFER-SCHEDULING", "No Change — Existing Coverage", "books/part-05-inference-system/56-inference-scheduling.md#L160", "books/part-02-model/20-sampling.md#L180; books/part-04-training-system/33-grpo.md#L1020", "调度章已把 reasoning token budget、stopping policy 与 expected value per token 作为 request-level control state。", "sample-optimal-length 自训练只提供一种长度 proposal；scheduler 仍拥有上线预算、SLO 与 harmful early-stop audit。", "Direct Evolution", "https://arxiv.org/html/2504.21370v1#S3", "https://arxiv.org/html/2504.21370v1#S4; https://arxiv.org/html/2504.21370v1#S5", "https://arxiv.org/html/2504.21370v1#S5.SS2; https://arxiv.org/html/2504.21370v1#S6", "Not Disclosed — exact-v1 does not identify a released implementation artifact", "reasoning 长度是受 workload 约束的可学习 stopping proposal，不是“越短越好”；上线仍需质量 guardrail、尾延迟和错误早停审计。", "作者搜索 sample optimal length 并训练模型在保持准确率时缩短输出，包含 out-of-domain 与 ablation。结果受选定数学任务、模型和 evaluator 限制；长度标签可能奖励跳步或格式捷径，旧的固定上限/自然 EOS 在低风险任务仍更简单。"),
    c("SF-2025-GALVATRON", "2504.21411", "Galvatron: An Automatic Distributed System for Efficient Foundation Model Training", "2025-04-30T08:11:45Z", (3,3,3), "TRAIN-DISTRIBUTED-TRAINING", "Integrate", "books/part-04-training-system/36-distributed-training.md#L610", "books/part-04-training-system/37-tensor-parallel.md#L1; books/part-04-training-system/38-pipeline-parallel.md#L1", "分布式训练章已有 cost model、collective 与 static/dynamic plan 边界，但自动 plan search 的状态 owner、校准与失效回退尚未形成完整链条。", "增加 planner 分支：冻结 model/hardware/memory/communication profile，搜索 DP/TP/PP/sharding 组合；runtime 执行并用真实 telemetry 校准，预测失真时回到已验证静态 plan。", "Direct Evolution", "https://arxiv.org/html/2504.21411v1#S2; https://arxiv.org/html/2504.21411v1#S3", "https://arxiv.org/html/2504.21411v1#S4", "https://arxiv.org/html/2504.21411v1#S5", "https://github.com/PKU-DAIR/Hetu-Galvatron — repository linked from exact-v1", "自动并行 planner 只拥有候选 plan；model shape、cluster topology、memory cap 和 collective profile 构成 plan identity，runtime telemetry 与 fallback 才拥有上线真值。", "Galvatron 把 hybrid parallelism 搜索与执行 workflow 连接，并在作者 benchmark 下比较训练效率。它不证明 cost model 可跨拓扑、版本和动态故障稳定；profiling 成本、search explosion、错误 memory estimate 与 process-group churn 是新增 failure mode，固定静态 plan 在稳定 workload 下仍合理。", override="knowledge_gap"),
    c("SF-2025-RWKV-X", "2504.21463", "RWKV-X: A Linear Complexity Hybrid Language Model", "2025-04-30T09:38:17Z", (2,2,2), "MODEL-LONG-CONTEXT", "No Change — Existing Coverage", "books/part-02-model/22-long-context.md#L1", "books/part-02-model/15-attention.md#L1; books/part-05-inference-system/45-why-kv-cache-speeds-up.md#L1", "Long-context 章节已把 recurrent/linear state 与 sparse attention 作为替代分支，并要求保留 cache/state identity。", "top-k chunk sparse attention 加 RWKV block 是该分支的组合实例，不改变 owner。", "Alternative Branch", "https://arxiv.org/html/2504.21463v1#S3; https://arxiv.org/html/2504.21463v1#S3.SS2.SSS1", "https://arxiv.org/html/2504.21463v1#S4; https://arxiv.org/html/2504.21463v1#A2", "https://arxiv.org/html/2504.21463v1#S5; https://arxiv.org/html/2504.21463v1#A3", "https://github.com/howard-hou/RWKV-X — repository linked from exact-v1", "长上下文可以组合 recurrent linear state 与少量 sparse attention，但 active chunks、KV/state layout 和 continual-pretraining revision 必须共同定义运行时 identity。", "论文给出 chunk sparse attention、KV 管理、复杂度和 continual pretraining，并测量长短 context 与效率。作者实验不证明 top-k retrieval 在所有任务保留关键信息；routing error、chunk metadata 与 hybrid kernel complexity 是代价，全 attention 在短上下文/高精度需求下仍成立。"),
    c("SF-2025-RAGFORENSICS", "2504.21668", "Traceback of Poisoning Attacks to Retrieval-Augmented Generation", "2025-04-30T14:10:02Z", (2,3,2), "PLATFORM-SECURITY", "No Change — Existing Coverage", "books/part-06-ai-infrastructure/72-security.md#L1", "books/part-07-agent/76-rag.md#L1; books/part-06-ai-infrastructure/69-trace.md#L1", "Security/RAG 章节已要求 document provenance、retrieval trace、attack surface 与 quarantine 分离。", "RAGForensics 的 traceback 是已有 provenance contract 的诊断实现，不把相似度归因升级为因果证明。", "Layering / Dependency", "https://arxiv.org/html/2504.21668v1#S3; https://arxiv.org/html/2504.21668v1#S4", "https://arxiv.org/html/2504.21668v1#S5", "https://arxiv.org/html/2504.21668v1#S6; https://arxiv.org/html/2504.21668v1#S7", "Not Disclosed — exact-v1 does not identify a released artifact", "RAG poisoning diagnosis 必须回溯 query、retrieved document、index revision 与 generated claim；traceback score 只拥有调查优先级，不拥有删除或定罪 authority。", "论文定义 threat model，组合可疑文本定位与实验评估，并测试 adaptive attacks。证据限于选定攻击、corpus、retriever 与 generator；false attribution、adaptive evasion 和昂贵 replay 要求人工/独立证据，简单 allowlist 和 immutable corpus 在高风险域仍适用。"),
    c("SF-2025-WEBTHINKER", "2504.21776", "WebThinker: Empowering Large Reasoning Models with Deep Research Capability", "2025-04-30T16:25:25Z", (2,3,2), "AGENT-WORKFLOW", "No Change — Existing Coverage", "books/part-07-agent/81-workflow.md#L1", "books/part-07-agent/76-rag.md#L1; books/part-06-ai-infrastructure/66-evaluation-system.md#L280", "Workflow/RAG 章节已拥有 plan-search-draft、evidence provenance、tool receipt 与 report-level verification。", "WebThinker 的 think-search-draft 与 RL 是该工作流的受限实例，不新增可绕过证据 gate 的自治 authority。", "Direct Evolution", "https://arxiv.org/html/2504.21776v1#S3; https://arxiv.org/html/2504.21776v1#A1", "https://arxiv.org/html/2504.21776v1#S4; https://arxiv.org/html/2504.21776v1#S4.SS7", "https://arxiv.org/html/2504.21776v1#S5; https://arxiv.org/html/2504.21776v1#A3.SS4", "https://github.com/RUC-NLPIR/WebThinker — repository linked from exact-v1", "Deep Research 是 durable evidence workflow：搜索、读取、草稿与最终 claim 必须共享 source/version lineage，模型只拥有 proposal，工具结果和 verifier 拥有 evidence。", "论文组合 Deep Web Explorer、think-search-draft 与 tool-use RL，在复杂问答和报告生成任务上比较并做 ablation。它不证明 web evidence 正确、引用完整或开放网络安全；搜索漂移、citation laundering、judge bias 与长轨迹成本仍需平台 gate。"),
    c("SF-2025-SWE-SMITH", "2504.21798", "SWE-smith: Scaling Data for Software Engineering Agents", "2025-04-30T16:56:06Z", (3,3,3), "TRAIN-DATA", "No Change — Existing Coverage", "books/part-04-training-system/27-data.md#L280", "books/part-06-ai-infrastructure/66-evaluation-system.md#L790; books/part-07-agent/81-workflow.md#L1", "Data 章已把 executable mutation、environment/test oracle、trajectory 与 lineage 作为 agentic data factory。", "SWE-smith 已被该命题承载；本轮只重建 exact-day provenance，不重复追加论文清单。", "Direct Evolution", "https://arxiv.org/html/2504.21798v1#S2; https://arxiv.org/html/2504.21798v1#A1; https://arxiv.org/html/2504.21798v1#A2", "https://arxiv.org/html/2504.21798v1#S3; https://arxiv.org/html/2504.21798v1#S4; https://arxiv.org/html/2504.21798v1#A6", "https://arxiv.org/html/2504.21798v1#S6; https://arxiv.org/html/2504.21798v1#A6.SS3.SSS3", "https://github.com/SWE-bench/SWE-smith — official repository identified by the manuscript/project", "可扩展 software-agent data 需要 repository commit、container、mutation、fail-to-pass test、issue 与 trajectory 的联合 identity；test oracle 而不是 LLM judge 拥有样本 admission。", "论文构建 executable task factory 并用 128 个 repositories、50,137 instances 和下游训练测试其数据效用。结果不证明 synthetic bug 等同真实 issue 或跨语言泛化；container supply chain、test inadequacy、license 和 storage 成本是新增风险，真实 PR 仍是 calibration branch。"),
    c("SF-2025-DEEPSEEK-PROVER-V2", "2504.21801", "DeepSeek-Prover-V2: Advancing Formal Mathematical Reasoning via Reinforcement Learning for Subgoal Decomposition", "2025-04-30T16:57:48Z", (3,3,3), "TRAIN-GRPO", "No Change — Existing Coverage", "books/part-04-training-system/33-grpo.md#L940", "books/part-04-training-system/29-sft.md#L1; books/part-06-ai-infrastructure/66-evaluation-system.md#L750", "GRPO/Evaluation 已把 subgoal boundary、cold start、outcome verifier 与 reward hacking 边界写入主线。", "Lean proof checking 是 executable verifier 分支；自然语言 sketch 和 recursive subgoal search 不取得 truth authority。", "Direct Evolution", "https://arxiv.org/html/2504.21801v1#S2; https://arxiv.org/html/2504.21801v1#S2.SS1", "https://arxiv.org/html/2504.21801v1#S3; https://arxiv.org/html/2504.21801v1#S3.SS4", "https://arxiv.org/html/2504.21801v1#S4; https://arxiv.org/html/2504.21801v1#A3", "https://github.com/deepseek-ai/DeepSeek-Prover-V2 — official repository linked from exact-v1", "形式推理训练应把自然语言 sketch、subgoal proposal、Lean environment 与 executable verdict 分开；verifier 拥有 proof acceptance，policy 只拥有搜索 proposal。", "论文用 recursive subgoal decomposition、synthetic cold start、expert iteration 和 RL 训练 prover，并在 MiniF2F/大学/组合题上评估。证据受 Lean version、sampling budget 和 benchmark formalization 限制；vacuous proof、benchmark bug、verifier exploitation 与高 rollout cost 不允许外推为通用 reasoning correctness。"),
    c("SF-2025-WHOWHEN", "2505.00212", "Which Agent Causes Task Failures and When?", "2025-04-30T23:09:44Z", (3,3,3), "PLATFORM-TRACE", "No Change — Existing Coverage", "books/part-06-ai-infrastructure/69-trace.md#L180", "books/part-06-ai-infrastructure/67-monitoring.md#L1; books/part-07-agent/82-multi-agent.md#L1", "Trace 章已区分 immutable event、step/agent attribution、diagnostic confidence 与因果 authority。", "Who&When 的 all-at-once、stepwise 与 binary-search judge 已作为 failure attribution 边界被承载。", "Layering / Dependency", "https://arxiv.org/html/2505.00212v1#S2; https://arxiv.org/html/2505.00212v1#S3; https://arxiv.org/html/2505.00212v1#A2", "https://arxiv.org/html/2505.00212v1#S4; https://arxiv.org/html/2505.00212v1#A4", "https://arxiv.org/html/2505.00212v1#S6; https://arxiv.org/html/2505.00212v1#S7", "https://github.com/mingyin1/Agents_Failure_Attribution — repository linked from exact-v1", "多 Agent debugging 必须保存 agent、step、tool result 与 shared-state revision；LLM attribution 只产生 diagnostic evidence，不能直接成为 rollback 或责任裁决。", "论文标注 127 个 systems、184 个 failed tasks，比较三种定位流程与 context/cost sensitivity。结果显示全局 receptive field、局部 step precision 和 token cost 冲突；judge bias、shared cause、single-blame 标签与隐私限制因果解释。"),
    c("SF-2025-ML-DRIFT", "2505.00232", "Scaling On-Device GPU Inference for Large Generative Models", "2025-05-01T00:44:13Z", (3,3,3), "INFER-TENSORRT-LLM", "No Change — Existing Coverage", "books/part-05-inference-system/49-tensorrt-llm.md#L20", "books/part-05-inference-system/45-why-kv-cache-speeds-up.md#L1; books/part-05-inference-system/54-gpu-memory.md#L1", "Execution 章已把 logical tensor、device-specific layout、memory placement、fusion 与 prefill/decode 分支纳入 plan identity。", "ML Drift 的 tensor virtualization、coordinate translation 与 stage-aware optimization 是同一机制在 heterogeneous on-device GPU 上的实现。", "Layering / Dependency", "https://arxiv.org/html/2505.00232v1#S3; https://arxiv.org/html/2505.00232v1#S3.SS7; https://arxiv.org/html/2505.00232v1#S3.SS8", "https://arxiv.org/html/2505.00232v1#S4; https://arxiv.org/html/2505.00232v1#S4.SS2", "https://arxiv.org/html/2505.00232v1#S5", "Not Disclosed — exact-v1 describes the framework but does not identify a frozen public ML Drift repository", "on-device runtime 要把逻辑 tensor 与物理 GPU object 分离，再由 device specialization、memory manager、fusion 和 prefill/decode plan materialize；模型语义不应绑定单一 GPU API。", "论文跨 mobile、desktop/laptop 与 Apple Silicon 测试 diffusion/LLM，并给出 virtualization、coordinate translation、memory、fusion 和 KV layout。作者 benchmark 受设备、driver、model 与 precision 约束；跨设备实现复杂度、memory pressure 和 fallback coverage 是代价。"),
    c("SF-2025-TRAJ-BOOTSTRAP", "2505.00234", "Self-Generated In-Context Examples Improve LLM Agents for Sequential Decision-Making Tasks", "2025-05-01T00:48:12Z", (2,2,3), "AGENT-MEMORY", "No Change — Existing Coverage", "books/part-07-agent/77-memory.md#L1", "books/part-07-agent/76-rag.md#L1; books/part-07-agent/81-workflow.md#L1", "Memory 章已把 successful trajectory 转换为可撤销 derived memory，并要求 provenance、selection、forgetting 与 held-out evaluation。", "Traj-Bootstrap 的 database/exemplar selection 是已有 derived-memory admission 的实例。", "Direct Evolution", "https://arxiv.org/html/2505.00234v1#S5; https://arxiv.org/html/2505.00234v1#A4", "https://arxiv.org/html/2505.00234v1#S6; https://arxiv.org/html/2505.00234v1#A5; https://arxiv.org/html/2505.00234v1#A6", "https://arxiv.org/html/2505.00234v1#S7; https://arxiv.org/html/2505.00234v1#A2", "Not Disclosed — exact-v1 does not identify a released trajectory database implementation", "成功轨迹可以成为下次决策的候选 memory，但 source task、policy version、outcome verifier、selection 与 deletion policy 必须随 exemplar 保存；成功一次不等于普适规则。", "论文从 agent 自己的成功 experience 构建数据库并做 database/exemplar selection，在 ALFWorld、Wordcraft、InterCode-SQL 评估。收益受 benchmark、initial examples、retriever 和 growing-context cost 限制；feedback loop 会固化偶然成功或污染，人工示例在高风险/低数据时仍合理。"),
    c("SF-2025-MUTEDRAG-AVAILABILITY", "2504.21680", "Hoist with His Own Petard: Inducing Guardrails to Facilitate Denial-of-Service Attacks on Retrieval-Augmented Generation of LLMs", "2025-04-30T14:18:11Z", (3,3,2), "PLATFORM-SECURITY", "No Change — Existing Coverage", "books/part-06-ai-infrastructure/72-security.md#L1", "books/part-07-agent/76-rag.md#L1; books/part-06-ai-infrastructure/69-trace.md#L1", "Security 与 RAG 章节已把 retrieved content 视为不可信输入，并要求 provenance、admission、policy decision 与 availability outcome 可追踪。", "MutedRAG 进一步证明 safety guardrail 本身可以被对抗性 retrieved text 触发而成为 availability attack surface；这强化既有命题，但不改变 owner。", "Direct Evolution", "https://arxiv.org/html/2504.21680v1#S3", "https://arxiv.org/html/2504.21680v1#S4", "https://arxiv.org/html/2504.21680v1#S5; https://arxiv.org/html/2504.21680v1#S6", "Not Disclosed — exact-v1 does not identify a frozen public attack/evaluation artifact", "RAG 安全不能只测恶意内容是否被拒绝，还要把恶意检索内容诱发的正常请求拒绝视为 availability failure；retrieval hit、guardrail decision 与 final refusal 必须分开记录。", "论文给出攻击目标、黑盒/白盒路径和多数据集、多模型实验，并讨论若干防御。证据只支持论文所测 retriever、generator、guardrail 与攻击模板；它不证明任意安全过滤器都可被同样利用，也不证明内容过滤能无损修复。更严格 admission 会换来 false positive、延迟与维护成本；高风险域的 curated corpus/allowlist 仍是合理共存分支。"),
    c("SF-2025-LONGFUNCEVAL", "2505.10570", "LongFuncEval: Measuring the effectiveness of long context models for function calling", "2025-04-30T15:21:51Z", (2,2,2), "PLATFORM-EVALUATION-SYSTEM", "No Change — Existing Coverage", "books/part-06-ai-infrastructure/66-evaluation-system.md#L1", "books/part-07-agent/78-tool-use.md#L1; books/part-07-agent/75-context.md#L1", "Evaluation 章已要求冻结 tool/schema、上下文构成、state evolution、evaluator 与执行结果，且不把单一聚合分数当成能力本体。", "LongFuncEval 把长上下文 function calling 拆成大工具目录、长工具返回与多轮历史三种压力，是既有 evaluation contract 的具体化。", "Layering / Dependency", "https://arxiv.org/html/2505.10570v1#S3; https://arxiv.org/html/2505.10570v1#S4", "https://arxiv.org/html/2505.10570v1#S5", "https://arxiv.org/html/2505.10570v1#S6; Not Disclosed — exact-v1 has no dedicated limitations section", "https://github.com/ShishirPatil/gorilla/ — BFCL repository linked by the manuscript; paper-specific frozen exact-v1 dataset artifact Not Disclosed", "长上下文 function-calling 评测必须分别改变 tool catalog size、tool-response length/answer position 与 multi-turn history，并冻结 schema、parser、model 与 evaluator；一个 long-context headline score 不能定位系统瓶颈。", "论文构造三类 workload 并比较模型在不同上下文压力下的 function-calling 成功。它证明的是冻结 benchmark contract 下的失效切片，不证明真实工具副作用、权限、网络故障或生产 SLO；扩充工具/历史会提高覆盖，也会增加 schema 检索、parser 与 evaluator 混杂。"),
    c("SF-2025-VDDP", "2504.21752", "VDDP: Verifiable Distributed Differential Privacy under the Client-Server-Verifier Setup", "2025-04-30T15:46:55Z", (3,3,3), "PLATFORM-SECURITY", "No Change — Existing Coverage", "books/part-06-ai-infrastructure/72-security.md#L1", "books/part-04-training-system/27-data.md#L1; books/part-06-ai-infrastructure/71-tenancy.md#L1", "Security 章已要求 privacy claim 绑定可执行 policy、可信边界、receipt 与独立验证，而不是由执行方自我声明。", "VDDP 用 client/server/verifier 分权、可验证随机机制与密码学证明具体化该 contract；新增的是机制证据，不是新的知识 owner。", "Layering / Dependency", "https://arxiv.org/pdf/2504.21752v1 — §3 Problem Formulation; §4 Verifiable Distributed Discrete Laplace Mechanism; §5 Verifiable Randomized Response", "https://arxiv.org/pdf/2504.21752v1 — §6 Evaluation", "https://arxiv.org/pdf/2504.21752v1 — §8 Conclusion and Open Questions; Appendix C.5", "Artifact announced for publication at https://github.com/sjtu-ipads/VDDP ; no frozen exact-v1 artifact was available for this review", "分布式差分隐私不能让 server 同时拥有随机机制执行与合规证明；mechanism revision、随机性来源、collusion model、proof/receipt 与 verifier identity 必须共同定义 privacy evidence。", "论文形式化 client-server-verifier 设置，构建可验证离散 Laplace 与 randomized response，并测量密码学开销。它不消除 verifier/collusion 假设，也不证明部署中的 data pipeline、side channel 或 privacy budget composition 正确；证明成本、可信设置与系统复杂度是代价，受控环境下的 trusted aggregator 仍可能更简单。"),
    c("SF-2025-CORAL-PROTOCOL", "2505.00749", "Coral Protocol: Open Infrastructure Connecting The Internet of Agents", "2025-04-30T22:17:13Z", (2,2,1), "AGENT-MCP", "No Change — Existing Coverage", "books/part-07-agent/83-mcp.md#L1", "books/part-07-agent/82-multi-agent.md#L1; books/part-07-agent/84-agent-platform.md#L1", "MCP/Multi-Agent 章节已明确连接协议只标准化 discovery、message 与 tool/resource interface，不授予信任、workflow commit 或业务授权。", "Coral 把 agent、MCP server、coordination server、team formation 与跨域通信画成一套 architecture；其接口分层印证既有边界，但没有足够实证改变长期结论。", "Explanatory Analogy", "https://arxiv.org/html/2505.00749v1#S4; https://arxiv.org/html/2505.00749v1#S5", "https://arxiv.org/html/2505.00749v1#S6", "https://arxiv.org/html/2505.00749v1#S7; Not Disclosed — exact-v1 has no rigorous matched benchmark or dedicated limitations section", "Not Disclosed — exact-v1 describes a planned/open infrastructure but does not identify a frozen implementation release used by this review", "Agent interoperability protocol 只拥有 message/discovery/coordination interface；authoritative workflow state、identity、authorization、payment settlement 与 safety commit 必须留在可审计 platform owner。", "论文描述 ecosystem、component architecture、MCP/tool connection、server 与一个 real-world application narrative。它主要是 architecture/spec proposal，没有 matched benchmark、failure injection 或 production evidence；因此只能证明一种接口组合的可表达性，不能证明安全、互操作、性能或经济层成立。" , benchmark="no"),
]


BENCH = {
    "SF-2025-COSMOS-ADAPTATION": ("11 个 NLP classification tasks；fine-tuning、retrieval-augmented ICL 与组合策略", "Mistral-7B、Llama-2/3、Pythia 等论文 roster", "NVIDIA A100 80GB（Appendix B）", "Not Disclosed", "task examples / retrieval context；token length Not Disclosed", "class prediction", "training/retrieval sweeps；统一 batch Not Disclosed", "offline", "quality/cost prediction error 与 strategy regret；无生产阈值", "task metric + measured/estimated cost"),
    "SF-2025-ZIPLLM-STORAGE": ("Hugging Face LLM family storage、dedup/compression 与 materialization/serving throughput", "多 base/fine-tuned LLM families", "storage server / GPU setup 见 §5.1；具体 GPU 型号按表，正文不形成通用 hardware claim", "lossless bytes；model precision follows artifacts", "tensor/chunk corpus", "materialized model bytes", "storage pipeline", "offline storage + load", "reduction ratio、compression/decompression throughput；无生产 SLO", "byte equality + throughput"),
    "SF-2025-BAYES-EVAL-CONFIDENCE": ("有限 query 的 LLM pairwise/ranking evaluation", "anchor 与 candidate LLM roster 见 §3", "Not Disclosed", "Not Disclosed", "constructed query set", "model answers/judgments", "limited samples", "offline", "posterior ranking confidence；无 production threshold", "Bayesian posterior + comparison baselines"),
    "SF-2025-PHI4-REASONING": ("math/code/science reasoning、general 与 safety evaluation", "Phi-4-reasoning、Phi-4-reasoning-plus 与 baseline models", "Not Disclosed", "Not Disclosed", "最大 context 32K；per-task prompt length Not Disclosed", "long reasoning response", "Not Disclosed", "offline sampling", "accuracy/pass metrics；无 latency SLO", "benchmark scorers、best-of-5 / distribution analysis"),
    "SF-2025-SHORTERBETTER": ("数学 reasoning 的 sample-optimal-length search 与 OOD evaluation", "Qwen2.5-based reasoning models / paper roster", "Not Disclosed", "Not Disclosed", "problem prompt", "variable CoT length", "Not Disclosed", "offline", "accuracy 与 generated token length", "task exact-answer scorer"),
    "SF-2025-GALVATRON": ("hybrid-parallel plan search 与 foundation-model training", "Transformer family configs in §4", "multi-GPU clusters in §4; exact topology bound to each experiment", "Not Disclosed", "model shapes / sequence configs", "training step", "plan-specific", "distributed workers", "throughput/memory；无 production SLO", "runtime profiler + measured training throughput"),
    "SF-2025-RWKV-X": ("long-context LM quality、efficiency 与 ablations", "RWKV-X sizes and Transformer/RWKV baselines", "training/evaluation hardware in Appendix A/B", "Not Disclosed", "short context to 1M-token tests per paper", "LM token prediction", "Not Disclosed", "offline", "perplexity/accuracy/throughput/memory", "task metrics + runtime measurement"),
    "SF-2025-RAGFORENSICS": ("poisoned RAG traceback under baseline/adaptive attacks", "retriever/generator combinations in §5.1", "Not Disclosed", "Not Disclosed", "query + corpus documents", "generated answer + suspect ranking", "Not Disclosed", "offline", "traceback metrics and attack success；无 production SLO", "known injected poison ground truth"),
    "SF-2025-WEBTHINKER": ("complex reasoning + scientific report generation with web tools", "QwQ/DeepSeek-R1-based LRMs and baselines", "Not Disclosed", "Not Disclosed", "web evidence and long prompts；length by task", "answer/report", "Not Disclosed", "tool loop", "task score/report judge；无 production SLO", "task scorer + model-based report evaluation"),
    "SF-2025-SWE-SMITH": ("50,137 executable SWE tasks / 128 repos；RFT on 5,016 trajectories", "Qwen2.5-Coder 7B/32B", "2–8×H100 80GB", "Not Disclosed", "max context 32,768", "agent patch trajectory", "training setup in Appendix F", "offline agent runs", "SWE-bench Verified Pass@1", "repository tests / harness"),
    "SF-2025-DEEPSEEK-PROVER-V2": ("Lean theorem proving、MiniF2F/ProverBench/combinatorial tasks", "DeepSeek-Prover-V2 7B/671B", "Not Disclosed", "Not Disclosed", "SFT 16,384；GRPO max 32,768", "Lean proof", "GRPO 256 prompts ×32 proofs/iteration", "offline sampling", "Pass@k / proof success；无 latency SLO", "Lean 4.9.0-rc2 verifier"),
    "SF-2025-WHOWHEN": ("127 multi-agent systems、184 failed tasks、step/agent attribution", "GPT-4o and open/reasoning judge roster", "Not Disclosed", "Not Disclosed", "full or partial trace", "agent + decisive step", "184 annotated failures", "offline", "agent/step accuracy、tolerance、token cost", "three-expert annotation consensus"),
    "SF-2025-ML-DRIFT": ("large diffusion/LLM inference across mobile、desktop/laptop、Apple Silicon GPUs", "diffusion and LLM roster in §4", "multiple mobile GPUs、desktop/laptop GPUs、Apple Silicon", "model/device-specific；not normalized", "model/input-specific", "image/audio/text generation", "device-specific", "single-device inference", "latency/memory/throughput；无 production threshold", "runtime timing + output checks"),
    "SF-2025-TRAJ-BOOTSTRAP": ("ALFWorld、Wordcraft、InterCode-SQL sequential decision tasks", "LLM agent backbones in §6.1", "Appendix F computational resources", "Not Disclosed", "task observation/action history + retrieved exemplars", "agent action trajectory", "population/retrieval configs", "sequential episodes", "task success and quality metrics", "environment/task evaluator"),
    "SF-2025-MUTEDRAG-AVAILABILITY": ("RAG denial-of-service attacks induced through safety guardrails across three datasets", "8 LLMs / paper guardrail and RAG configurations", "Not Disclosed", "Not Disclosed", "query + retrieved adversarial text", "answer or guardrail refusal", "attack/evaluation batches by §4", "offline", "attack success / refusal availability metrics；无 production SLO", "known attack condition + task/refusal outcomes"),
    "SF-2025-LONGFUNCEVAL": ("large tool catalog、long tool responses/answer position、long multi-turn function calling", "long-context model roster in §4", "Not Disclosed", "Not Disclosed", "three independently varied long-context workloads", "function call / final answer", "benchmark splits in §4", "offline", "function-call and answer correctness；无 production latency SLO", "BFCL-derived benchmark scorer / task oracle"),
    "SF-2025-VDDP": ("verifiable distributed discrete-Laplace and randomized-response mechanisms", "cryptographic protocol implementations", "Intel Xeon Platinum 8358, 32 cores, 231 GB RAM", "integer/cryptographic protocol arithmetic", "client records / protocol parameters", "DP aggregate or randomized response + proof", "microbenchmark configs in §6", "client-server-verifier protocol", "proof verification time、communication and mechanism overhead；无 production SLO", "cryptographic verifier + mechanism correctness checks"),
}


def marker(ref, body):
    return f"<!-- {ref}:start -->{body}<!-- {ref}:end -->"


def body_hash(body):
    normalized = unicodedata.normalize("NFC", body.replace("\r\n", "\n").replace("\r", "\n"))
    lines = [line.rstrip() for line in normalized.split("\n")]
    while lines and not lines[0]: lines.pop(0)
    while lines and not lines[-1]: lines.pop()
    return hashlib.sha256("\n".join(lines).encode()).hexdigest()


def provenance(x, review_body):
    def multi(value):
        return ";".join(sorted(unicodedata.normalize("NFC", i.strip()) for i in value.split(";") if i.strip() and i.strip() not in {"-","—","n/a","N/A","Not Applicable"}))
    primary = f"arXiv:{x['aid']}v1"
    reviewed = f"SRC-ARXIV@{primary}"
    parts = ["review-completion-v1", x["fid"], f"paper-v1:{x['aid']}", primary, "SRC-ARXIV", primary, reviewed, x["route"]]
    if x["override"] != "none": parts.append(f"review-override:{x['override']}")
    parts += [multi(x["method"]), multi(x["evaluation"]), multi(x["limits"]), multi(x["artifact"]), f"claim:{x['fid']}", f"review:{x['fid']}", f"review-body-sha256:{body_hash(review_body)}"]
    return "RP-" + hashlib.sha256("|".join(parts).encode()).hexdigest()[:16]


def main():
    candidate_ids = "<br>".join(x["fid"] for x in C)
    denominator = "DEN-20250501-" + hashlib.sha256((candidate_ids + "2baec2f5e321c55bba9c4fa4e839dab866b43827cddf185cc0f7535239968b01").encode()).hexdigest()[:20]
    lines = [
        "# Daily Research — 2025-05-01", "", "**Research Date:** 2025-05-01", "", "**Timezone:** Asia/Shanghai", "",
        "**Strict Window:** 2025-04-30 09:00:00 ～ 2025-05-01 09:00:00（北京时间，左闭右开）", "",
        "**Contract:** V2.1 Full Replay", "",
        "**Status:** In Progress；Coverage=Closed、Evidence=Passed、Books=Open（3 项已写回，等待独立 Books 语义审计），fresh-context Semantic Audit 状态见第 7 节", "",
        "## Executive Summary", "",
        "本轮不是从 W18 的旧 `/30` 评分反推日报，而是从严格窗口的官方 arXiv Atom 快照重新建立分母。快照包含 853 条 raw identities：217 条 Core Daily 逐项完成 title+abstract 语义筛选；122 条 keyword-routed 分类中 107 条触发系统关键词并继续语义判断；514 条非注册分类完成 identity/date/topic closure。首次冻结后保留 15 个 Source Family；fresh-context 漏检审计发现 MutedRAG、LongFuncEval、VDDP 与 Coral Protocol 四个 false negative，完成 exact-v1 Review 后重新冻结为 19 个（2.23%），其余 834 项都有 family-specific pre-denominator closure。", "",
        "15 个候选均已读取 exact-v1 HTML 的 Method、evaluation、limitations/结论及已公开 artifact，完成 V2 三维评分、route-matched Review、Benchmark Contract 和 Books Comparison。最强的长期线索是：训练系统从人工并行组合推进到 profile/search/telemetry/fallback 的 plan control；模型 artifact store 从文件级对象推进到 tensor/delta 的物理共享、但不合并逻辑身份；端侧推理把 logical tensor 与 device object 解耦。SWE-smith、DeepSeek-Prover、Who&When、WebThinker 等已由 Books 现有主线完整承载。", "",
        "当前 Coverage 与 Evidence Gate 已闭合。Books 比较发现 COSMOS、ZipLLM 与 Galvatron 三项可定位长期增量；root 已把三项分别写入 Ch70、Ch59 与 Ch36。本 worker 只同步写回事实，不自签 Books audit；Books Gate 保持 Open，等待另一位 agent 重新读取 owner 与相邻章节并确认语义绑定。", "",
        "## 1. Coverage", "", "<!-- validator:report-metadata-v2 -->",
        "| Field | Value |", "| --- | --- |", "| Contract Version | V2.1 |", "| Score Schema | V2 |", "| Report Type | Daily |", "| Window Start | 2025-05-01 |", "| Window End | 2025-05-01 |", "| Registry Version | 2026-08-25 |", "| Coverage Mode | Full Replay |", "| Baseline Report | |", "| Changed Source IDs | |", "| Previous Denominator ID | |", f"| Denominator ID | {denominator} |", "| Denominator Frozen At | 2026-08-31T17:50:00+08:00 |", "| Completion Status | In Progress |", "| Coverage Gate | Closed |", "| Evidence Gate | Passed |", "| Books Gate | Open |", "",
        "### Source Coverage Receipt", "", "<!-- validator:source-coverage-v2 -->",
        "| Source ID | Window Start | Window End | Executed At | Endpoint / Filter | Result | Hits | Candidate Source Families | Pagination / Cursor | Window Watermark | Closure Evidence | Gap / Limitation ID |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        f"| SRC-ARXIV | 2025-04-30T09:00:00+08:00 | 2025-05-01T09:00:00+08:00 | 2026-08-31T17:23:00+08:00 | official Atom API `submittedDate:[202504300100 TO 202505010100]`; Core full semantic + registered keyword route | checked | 853 | {candidate_ids} | page=1; final_cursor=end; totalResults=853 | 2025-05-01T01:00:00Z | coverage:SRC-ARXIV:20250501 | — |", "",
        marker("coverage:SRC-ARXIV:20250501", "官方 Atom 快照 `arxiv-20250501.xml`（SHA-256 `2baec2f5e321c55bba9c4fa4e839dab866b43827cddf185cc0f7535239968b01`）返回 853/853；`screening-ledger.json` 保存 217 条 Core 逐项语义筛选、122 条注册分类路由（107 条 keyword-triggered）、19 retained 与 834 family-specific closure。首次冻结后的 fresh-context audit 发现并修复 4 个 false negative。"), "",
        "### Coverage Limitations", "",
        "- 当前来源注册表自 2026-08-25 生效，不能把后来新增的 organization/backstop 列表冒充 2025-05-01 当时已存在的确定性分母。本次以官方 arXiv exact-window 快照闭合论文 recall，并用 W18 只作 prior discovery baseline；MiMo/Amazon 等当日产品公告因缺公开机制留在 screening closure，不进入长期机制候选。", "- 853 是 raw identity denominator，不是候选数；非注册分类和未达到长期 AI-System admission 的论文均保留逐 family closure，而不是静默删除。", "",
        "## 2. Candidate Ledger", "", "<!-- validator:candidate-ledger-v2.1 -->",
        "| Source Family ID | Primary Identifier | Event Identity | Owner Week | First-public Date | Supporting Source IDs | Design Delta | System Reach | Durability | Total | Candidate State | Review Status | Access Status | Review Override | Review Ref | Owner Report Ref | Prior Review Ref | Reconciliation | Stable Node ID | Books Disposition | Books Review Ref | Benchmark Claim |",
        "| --- | --- | --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for x in C:
        dd,sr,dur=x["score"]
        lines.append(f"| {x['fid']} | arXiv:{x['aid']}v1 | paper-v1:{x['aid']} | 2025-W18 | {x['published'][:10]} | SRC-ARXIV | {dd} | {sr} | {dur} | {x['total']} | retained | {x['route']}_complete | accessible | {x['override']} | review:{x['fid']} | self | — | new_in_window | {x['node']} | {x['disposition']} | books-review:{x['fid']} | {x['benchmark']} |")
    lines += ["", "## 3. Review Completion Receipt", "", "<!-- validator:review-completion-v1 -->", "| Source Family ID | Review Provenance ID | Review Route | Primary Evidence Version | Reviewed Evidence Versions | Method / Identity Locators | Evaluation Locators | Limitations / Counterevidence Locators | Artifact Locators | Claim Boundary Ref | Completion Result |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    review_bodies={x['fid']:marker(f"claim:{x['fid']}",x['claim'])+x['review'] for x in C}
    for x in C:
        rp=provenance(x,review_bodies[x['fid']])
        lines.append(f"| {x['fid']} | {rp} | {x['route']} | arXiv:{x['aid']}v1 | SRC-ARXIV@arXiv:{x['aid']}v1 | {x['method']} | {x['evaluation']} | {x['limits']} | {x['artifact']} | claim:{x['fid']} | complete |")
    lines += ["", "### Source Reviews", ""]
    for x in C:
        lines += [marker(f"review:{x['fid']}",review_bodies[x['fid']]), ""]
    lines += ["## 4. Benchmark Contracts", "", "Benchmark 数字只属于 exact-v1 的模型、数据、硬件和 evaluator；未披露字段保持 `Not Disclosed`，不从相邻工作补齐。Nexus-Gen 只有 qualitative case study，因此 Candidate Ledger 明确写 `Benchmark Claim=no`。", "", "<!-- validator:benchmark-contract-v1 -->", "| Source Family ID | Workload | Model | Hardware | Precision | Input Length | Output Length | Batch | Concurrency | SLO | Evaluator |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for x in C:
        if x['fid'] in BENCH:
            lines.append("| " + x['fid'] + " | " + " | ".join(BENCH[x['fid']]) + " |")
    lines += ["", "## 5. Deep Analysis Selection", "", "<!-- validator:deep-analysis-selection-v1 -->", "| Source Family ID | Eligibility | Decision | Analysis Unit ID | Subsumed By | Priority Rationale | Narrative Ref |", "| --- | --- | --- | --- | --- | --- | --- |"]
    selected={"SF-2025-GALVATRON":"DA-TRAIN-PLAN-CONTROL","SF-2025-SWE-SMITH":"DA-EXECUTABLE-DATA","SF-2025-ML-DRIFT":"DA-DEVICE-RUNTIME"}
    for x in C:
        if x['total']>=7 or x['disposition']=='Integrate':
            elig=[]
            if x['total']>=7: elig.append('score_7_9')
            if x['override']!='none': elig.append('forced_review')
            if x['disposition']=='Integrate': elig.append('potential_books_delta')
            if x['fid'] in selected:
                unit=selected[x['fid']]
                rationale={"SF-2025-GALVATRON":"自动 parallel-plan control 同时改变 planner、runtime 与 telemetry ownership。","SF-2025-SWE-SMITH":"executable data factory 把 data identity、environment 与 verifier 串成一条长期链。","SF-2025-ML-DRIFT":"端侧 tensor virtualization 最清楚暴露模型语义与 device object 的解耦。"}[x['fid']]
                lines.append(f"| {x['fid']} | {';'.join(elig)} | selected | {unit} | — | {rationale} | analysis:{unit} |")
            else:
                lines.append(f"| {x['fid']} | {';'.join(elig)} | not_selected | — | — | 已完成 route-matched Review 与 Books 比较；长叙事容量优先给本日报三条跨边界控制链，不降低该 family 的证据状态。 | analysis-decision:{x['fid']} |")
    lines += ["", marker("analysis:DA-TRAIN-PLAN-CONTROL", "### Deep Analysis 1 — 从手工并行组合到可校准 plan control\n\n静态 DP/TP/PP 组合在模型 shape 和集群稳定时最容易验证，也能复用 process group。约束改变后，组合空间、memory cap 和 topology 使人工枚举昂贵；Galvatron 增加 profile/cost-model/search planner。planner 只提出候选，runtime telemetry 才能验证 predicted throughput/memory；版本或 topology 漂移时回退已验证静态 plan。收益是自动探索，代价是 profiling、search、错误模型和 plan churn。"), ""]
    for x in C:
        if x['total']>=7 or x['disposition']=='Integrate':
            if x['fid'] not in selected: lines += [marker(f"analysis-decision:{x['fid']}", "该 family 已完成全文审计；其长期命题由 Source Review 与 Books Comparison 承载，本日报不再重复一段论文摘要式 Deep Analysis。"), ""]
    lines += [marker("analysis:DA-EXECUTABLE-DATA", "### Deep Analysis 2 — 从文本样本到 executable data factory\n\n真实 PR 任务可信但稀缺，纯文本合成便宜却无法证明 patch 可执行。SWE-smith 把 repository commit、container、mutation、fail-to-pass tests、issue 与 trajectory 合成一个样本 identity，并让 test oracle 拥有 admission。它扩大规模，也引入 test inadequacy、synthetic distribution、license 和 container supply-chain 风险；真实 PR 仍是校准集。"), "", marker("analysis:DA-DEVICE-RUNTIME", "### Deep Analysis 3 — 从单一 GPU backend 到逻辑 tensor virtualization\n\n固定 backend 直接把 tensor 映射到 device object，简单但把模型图绑定硬件 API。端侧设备、memory 上限和 prefill/decode 差异迫使 runtime 分离 logical tensor 与 physical object，再以 coordinate translation、device specialization、fusion 和 KV layout materialize。收益是跨 GPU 覆盖，代价是 backend matrix、fallback 缺口和 device-specific correctness/性能验证。"), ""]
    lines += ["## 6. Books Comparison", "", "<!-- validator:books-comparison-v1 -->", "| Source Family ID | Stable Node ID | Target Chapter Ref | Adjacent Chapter Refs | Existing Proposition | New Evidence Delta | Evolution Relation | Decision | Books Review Ref |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for x in C:
        lines.append(f"| {x['fid']} | {x['node']} | {x['chapter']} | {x['adjacent']} | existing:{x['fid']} | delta:{x['fid']} | {x['relation']} | {x['disposition']} | books-review:{x['fid']} |")
    lines += ["", "三项 `Integrate` 的写回收据位于 `_sources/daily-v2.1-replay-202505/20250501/books-writeback-queue.md`。root 已完成正文写回；本 worker 不修改共享 Books，也不自签独立审计。另一位 agent 完成 owner/adjacent 语义复核前，Books Gate 保持 Open。", ""]
    for x in C:
        lines += [marker(f"books-review:{x['fid']}", marker(f"existing:{x['fid']}",x['existing'])+marker(f"delta:{x['fid']}",x['delta'])+f"演进关系为 {x['relation']}；目标 `{x['node']}` 与相邻章节已读。当前决定：`{x['disposition']}`。"), ""]
    lines += ["## 7. Semantic Audit", "", "本日由同一 worker 在首次冻结后清空中间候选假设，重新读取 853-row ledger 并针对安全、隐私、evaluation contract 与 agent protocol 高风险 closure 做漏检复核。该 pass 实际发现 4 个 false negative，已提升、完成 exact-v1 Review 并重新冻结分母；下表 `passed` 行只呈现修正后的未解决 finding（为零），历史发现与修复收据保留在本段及 ledger。该标识不声称存在第二个 reviewer，Books 独立审计仍由另一 agent 负责。", "", "<!-- validator:semantic-audit-v1 -->", "| Audit ID | Auditor | Scope | Reviewed Refs | Findings | Resolution | Status |", "| --- | --- | --- | --- | --- | --- | --- |", "| SA-20250501-COVERAGE | fresh-context:may01_direct_context_reset | coverage | coverage:SRC-ARXIV:20250501 | — | 首次冻结的 4 个 false negative（2504.21680、2505.10570、2504.21752、2505.00749）已提升并完成全文审计；重新冻结为 853 raw、339 registered routes、19 retained、834 closures。 | passed |", f"| SA-20250501-EVIDENCE | fresh-context:may01_direct_context_reset | evidence | {'; '.join('review:'+x['fid'] for x in C)} | — | 19/19 exact-v1 Review、版本、locator、claim boundary 与 benchmark fields 已复核。 | passed |", f"| SA-20250501-SELECTION | fresh-context:may01_direct_context_reset | deep_analysis_selection | validator:deep-analysis-selection-v1; analysis:DA-TRAIN-PLAN-CONTROL; analysis:DA-EXECUTABLE-DATA; analysis:DA-DEVICE-RUNTIME | — | 所有 score 7–9、forced review 与 potential Books delta 均有 selection disposition；仅三条长叙事，不以未选中代替 Review。 | passed |", f"| SA-20250501-BOOKS | fresh-context:pending_independent_books_reviewer | books | validator:books-comparison-v1; {'; '.join('books-review:'+x['fid'] for x in C)} | BOOKS-INDEPENDENT-AUDIT-20250501 | Ch70/59/36 写回已完成；等待另一 agent 重读 owner/adjacent 并验证三项语义绑定，本 worker 不自签。 | open |", "",
        "## 8. Ignored Noise", "", "834 个 pre-denominator closures 已保存在 `screening-ledger.json`，每项包含 identity、first-public timestamp、categories、route、family-specific closure reason 与 false-negative audit result。主要类别为非注册学科、垂直领域任务、secondary survey、局部 benchmark/dataset，以及没有改变 state/data/control ownership 的单点模型改进；这些项目没有被误写成低分候选，也没有被冒充全文审阅。", "",
        "## 9. Recommended Action", "", "1. 由另一 agent 独立读取 Ch70/59/36 的写回段及相邻章节，确认三项长期命题不是 trace-only，而是真正进入旧方案→约束变化→机制→代价/fallback 的正文链。", "2. 独立审计通过后，只同步 Books Audit 收据与 Final Status；若发现语义断裂，回到对应 owner 修订，不以文件中存在 Source Family ID 代替 Integration。", "3. Sunday Weekly 聚合时使用 19 个 Source Family ID 和真实 v1 date，不能继承 W18 `/30` 或重复计分。", "",
        "## 10. Repository Changes", "", "- 新建 2025-05-01 Daily 与 source packet。", "- 冻结官方 Atom XML、19 个候选的 exact-v1 primary packet（20 个 HTML/PDF files，其中 DeepSeek-Prover 同时保留 HTML 与 PDF）、SHA-256 manifest、853-row screening ledger 和 Books writeback receipt。", "- root 已分别更新 `70-cost.md`、`59-model-registry.md` 与 `36-distributed-training.md`；本 worker 仅观察并同步该事实，未修改共享 Books、ROADMAP 或 LEARNING_STATE。", "- 未 stage、commit 或 push。当前未完成项只有 `BOOKS-INDEPENDENT-AUDIT-20250501`，因此没有宣称 Complete。", "",
        "## 11. Open Questions", "", "- adaptation quality/cost predictor 在 dataset drift、价格变化和 failed training run 下怎样校准并决定 abstain？", "- tensor/delta dedup 怎样与 encryption、quantization、license、base deletion 和独立 rollback 共存？", "- parallel-plan cost model 在拓扑拥塞、heterogeneous accelerator 与 elastic failure 下何时失效？", "- on-device logical tensor virtualization 如何证明跨 backend numeric equivalence，并为 unsupported operator 设计安全 fallback？", "",
        "## 12. Sources", ""]
    for x in C:
        source_url = f"https://arxiv.org/pdf/{x['aid']}v1" if x['aid'] == "2504.21752" else f"https://arxiv.org/html/{x['aid']}v1"
        lines.append(f"- [{x['title']}]({source_url}) — arXiv:{x['aid']}v1；首次公开 `{x['published']}`；访问 2026-08-31。")
    lines += ["- [W18 prior discovery baseline](../../weekly/2025-W18/README.md) — 只用于历史对照，不继承 V1 评分或 Review 完成声明。", "", "## 13. Final Status", "", "- Completion Status = `In Progress`", "- Coverage = `Closed`", "- Evidence = `Passed`", "- Books = `Open`", "- unresolved findings = `1`（`BOOKS-INDEPENDENT-AUDIT-20250501`；三项正文已写回，只缺独立 owner/adjacent 语义验收）", "- 下一检查点：另一 agent 完成三项 Books fresh-context audit；通过后把日报同步为 `Complete / Closed / Passed / Passed`。", ""]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(REPORT)


if __name__ == "__main__":
    main()
